### ISSUE TITLE
build/test issues on WSL

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#11057]
Tracking current issues blocking CoreFx testing on Ubuntu on Windows:

(Note that basically nothing works prior to rs_preview build 14905, which introduced "restartable syscall" support.)

rs_preview build 14936 has a [known bug](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14936) that causes a BSOD when running our networking tests.
- [x] Need to update the dotnet cli to a more recent version with the "execstack" bit set correctly on native modules (https://github.com/dotnet/corefx/issues/11058).
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/967.
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/968.
- [x] System.Diagnostics.Process: https://github.com/Microsoft/BashOnWindows/issues/974
- [x] System.Diagnostics.Process: https://github.com/dotnet/corefx/issues/11072.
- [x] System.IO.Pipes: _hangs_ due to https://github.com/Microsoft/BashOnWindows/issues/975.
- [x] System.IO.Pipes: https://github.com/Microsoft/BashOnWindows/issues/1011
- [x] System.IO.Pipes: https://github.com/Microsoft/BashOnWindows/issues/1012
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/982.
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/987
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/989
- [x] System.Net.Sockets: https://github.com/Microsoft/BashOnWindows/issues/990
- [x] System.Linq.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Linq.Expressions.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Numerics.Vectors.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Runtime.Numerics.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.Dynamic.Runtime.Tests crashes due to https://github.com/Microsoft/BashOnWindows/issues/513
- [x] System.IO.FileSystem.Tests: https://github.com/Microsoft/BashOnWindows/issues/1008
- [x] System.IO.FileSystem.Watcher.Tests: https://github.com/Microsoft/BashOnWindows/issues/216 (fixed in Windows build 14926)
- [x] System.IO.FileSystem.DriveInfo.Tests: https://github.com/dotnet/corefx/issues/11570
- [x] System.Net.Ping.Functional.Tests: https://github.com/Microsoft/BashOnWindows/issues/561 (fixed in Windows build 14926)
- [x] System.Net.NetworkInformation.Functional.Tests: https://github.com/Microsoft/BashOnWindows/issues/308
- [x] Intermittent failures in System.Net.Http tests: https://github.com/Microsoft/BashOnWindows/issues/1068.
## Still need investigation:
- [x] NuGet package restore occasionally hangs.  Killing it and retrying usually gets past this.
- [x] Intermittent hangs in System.Net.Http tests.

**Comment by danmosemsft** [comment]
Complete support for bash on windows is not a 2.0 goal

**Comment by tarekgh** [comment]
marked as test bug as the failures we currently have are in tests. the other issues are external to WSL

**Comment by ViktorHofer** [comment]
51 tests are currently failing in WSL 1803. Attached the logs as txt.

```
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.IO.FileSystem.Tests  Total: 4027, Errors: 0, Failed: 11, Skipped: 15, Time: 146.386s [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.IO.FileSystem.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.IO.Pipes.Tests  Total: 507, Errors: 0, Failed: 6, Skipped: 0, Time: 13.152s [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.IO.Pipes.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.Net.Http.Unit.Tests  Total: 1626, Errors: 0, Failed: 17, Skipped: 0, Time: 114.423s [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.Net.Http.Unit.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.Net.Sockets.Tests  Total: 798, Errors: 0, Failed: 17, Skipped: 8, Time: 29.163s [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.Tests' please check /home/vihofer/corefx/bin/tests/System.IO.FileSystem.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.IO.Pipes.Tests' please check /home/vihofer/corefx/bin/tests/System.IO.Pipes.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.Net.Http.Unit.Tests' please check /home/vihofer/corefx/bin/tests/System.Net.Http.Unit.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.Net.Sockets.Tests' please check /home/vihofer/corefx/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/dir.traversal.targets(77,5): error : (No message specified) [/home/vihofer/corefx/src/tests.builds]    8 Warning(s)
```

[System.Net.Http.Unit.Tests.txt](https://github.com/dotnet/corefx/files/2402273/System.Net.Http.Unit.Tests.txt)
[System.Net.Sockets.Tests.txt](https://github.com/dotnet/corefx/files/2402274/System.Net.Sockets.Tests.txt)
[System.IO.FileSystem.Tests.txt](https://github.com/dotnet/corefx/files/2402275/System.IO.FileSystem.Tests.txt)
[System.IO.Pipes.Tests.txt](https://github.com/dotnet/corefx/files/2402276/System.IO.Pipes.Tests.txt)

**Comment by ViktorHofer** [comment]
What is left to do here:

1. Somebody should go through the remaining failures and either a) disable them, b) fix them if possible or c) create issues in the WSL repo and disable them temporarily with comments to the external tracking issues.
2. Go through the existing disabled WSL tests and re-enable them as most of them have been fixed and even more of them will be fixed with the next iteration of Windows 10.
3. Add WSL Ubuntu leg to CI that builds and tests. (cc @mmitche)

Marking as 3.0.

**Comment by ViktorHofer** [comment]
cc @joshfree

**Comment by danmosemsft** [comment]
Remaining list, I took out the GetSetTimes ones that @Anipik fixed.

```
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerIn_ClientOut.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOut_ClientIn.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOut_ClientOut.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOutRead_ClientInOutWrite.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerInOutWrite_ClientInOutRead.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerOut_ClientIn.Unix_OperationsOnNamedServerWithDisposedClient
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 0, firstLength: 10, secondPosition: 1, secondLength: 2)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 2, secondLength: 4)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 2, secondLength: 6)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 3, secondLength: 4)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 3, secondLength: 5)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 4, secondLength: 5)
System.IO.Tests.FileStream_LockUnlock.OverlappingRegionsFromOtherProcess_ThrowsException(fileLength: 10, firstPosition: 3, firstLength: 5, secondPosition: 4, secondLength: 6)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://127.0.0.1/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://128.0.0.1/\&quot;, shouldBypass: False)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://162.1.1.1/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://[2002::11]/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://[2607:f8B0:4005:80A::200E]/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://[2607:f8b0:4005:80a::200e]/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://[2a01:5b40:0:248::52]/\&quot;, shouldBypass: False)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://[::1]/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://bar.com/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://BAR.COM/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://bébé.eu/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://foo.com/\&quot;, shouldBypass: False)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://foo/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://localhost/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://www.bébé.eu/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://WWW.FOO.COM/\&quot;, shouldBypass: True)
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_Local_Bypassed(name: \&quot;http://www.foo.com/\&quot;, shouldBypass: True)
System.Net.Sockets.Tests.ExecutionContextFlowTest.SocketAsyncEventArgs_ExecutionContextFlowsAcrossSendAsyncOperation(suppressContext: True, sendMode: 2)
System.Net.Sockets.Tests.OSSupportTest.IOControl_SIOCATMARK_Unix_Success
System.Net.Sockets.Tests.SelectTest.Select_Error_OneReadyAtATime
System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize
System.Net.Sockets.Tests.SendReceive.SendIovMaxUdp_SuccessOrMessageSize
System.Net.Sockets.Tests.SendReceive.SocketSendWouldBlock_ReturnsBytesSent
System.Net.Sockets.Tests.SocketOptionNameTest.ExclusiveAddress_Default_Unix
System.Net.Sockets.Tests.SocketOptionNameTest.ExclusiveAddressUseTcp
System.Net.Sockets.Tests.SocketOptionNameTest.ReuseAddress(exclusiveAddressUse: null, firstSocketReuseAddress: True, secondSocketReuseAddress: True, expectFailure: False)
System.Net.Sockets.Tests.SocketOptionNameTest.SettingExclusiveAddress_SetsReuseAddress(value: 0)
System.Net.Sockets.Tests.SocketOptionNameTest.SettingExclusiveAddress_SetsReuseAddress(value: 1)
System.Net.Sockets.Tests.TcpClientTest.Roundtrip_ExclusiveAddressUse_GetEqualsSet_False
System.Net.Sockets.Tests.TcpClientTest.Roundtrip_ExclusiveAddressUse_GetEqualsSet_True
System.Net.Sockets.Tests.TcpListenerTest.Active_TrueWhileRunning(ctor: 0)
System.Net.Sockets.Tests.TcpListenerTest.Active_TrueWhileRunning(ctor: 1)
System.Net.Sockets.Tests.TcpListenerTest.Active_TrueWhileRunning(ctor: 2)
System.Net.Sockets.Tests.UdpClientTest.EnableBroadcast_Roundtrips
```

**Comment by ViktorHofer** [comment]
Changing milestone to future. Would be great to get test failures to zero but not a high-prio.

**Comment by ViktorHofer** [comment]
WSL2 runs on a fully supported Linux kernel which should behave like all other distros. I believe we don't need this work here anymore.

nit: we should remove the existing WSL conditions in source code.

**Comment by wfurt** [comment]
We still have tests disabled agains this issue. 
We should clean that up before closing this again.
