### ISSUE TITLE
Track implementation assemblies that should be merged

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11151]
At the lowest levels of CoreFx, our implementation assemblies are very fine-grained, making it difficult to do certain implementations.

For example, Environment lives in System.Runtime.Extensions.dll, which is at a lower-level than System.IO and System.IO.FileSystem.  That means on Unix when we need to read a configuration file in support of Environment.GetFolderPath, we have to do very strange contortions to make it work, e.g. including lots of duplicated code or writing custom I/O implementations, using reflection to find the relevant I/O types in another assembly, etc.  This leads to bloat, is fragile, etc.  We should look at recombining some of these implementation assemblies.

This issue is to help track such dependencies.
cc: @weshaggard, @danmosemsft, @ericstj, @KrzysztofCwalina 
- [ ] System.Runtime.Extensions needs access to file I/O to implement Environment.GetFolderPath on Unix (Directory.CreateDirectory and File.ReadAllLines are used)
- [ ] System.Runtime.Extensions needs access to Process to implement Environment.WorkingSet (Process.GetCurrentProcess().WorkingSet64 is used)
- [ ] ...

**Comment by jkotas** [comment]
- [ ] CoreRT: System.Private.CoreLib needs access to `List<T>` to implement `Collection<T>` constructor
- [ ] CoreRT: System.Private.CoreLib needs access to `EqualityComparer<T>` and `Comparer<T>` to implement methods on Array and other types

**Comment by weshaggard** [comment]
@jkotas - Those types should be moved into System.Runtime ref and System.Private.CoreLib implementation.

**Comment by jkotas** [comment]
Opened #11284

**Comment by ianhays** [comment]
- [ ] System.IO (StreamReader/StreamWriter) needs access to FileStream from System.IO.FileSystem

**Comment by JeremyKuhne** [comment]
Tagging myself as IO is a big part of this

**Comment by tarekgh** [comment]
@weshaggard what is left to be done for this issue?

**Comment by weshaggard** [comment]
We still need to do an audit and review these before shipping 2.0.

**Comment by tarekgh** [comment]
@weshaggard are you on track doing the audit and review? just asking as we are getting closer to deadline.

**Comment by weshaggard** [comment]
This is something I generally do incrementally as I review other changes but as we get closer to the release I will take a deeper dive into the dependencies to see if there is anything we should fix.

**Comment by weshaggard** [comment]
@jkotas @stephentoub after all the work it doesn't look like we ended up needing to move System.IO.FileSystem down lower. These System.Runtime.Extensions dependency seems to be the only one reaching for these higher level concepts (https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L85, https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L215). I think keeping System.IO.FileSystem a separate assembly has enough value to keep it separate, which means we can continue with reflection in these cases. What do you guys think?

Similar question for https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.cs#L187 Process.WorkingSet. I definitely don't want to merge Process down but do we feel the reflection code is acceptable? If not we can move to a shared code model. 

I think reflection is acceptable and should work for these dependencies for any shared framework application. The only cases where they might not exist is for standalone applications that trim away the higher level libraries.

**Comment by stephentoub** [comment]
I don't love it, but at this point I'm ok sticking with the reflection approach for 2.0.

**Comment by weshaggard** [comment]
@stephentoub what would your idea solution look like? Would you merge everything down lower?

**Comment by stephentoub** [comment]
Yeah, at this point I'm not clear on what the separation really buys us.

**Comment by jkotas** [comment]
> I'm not clear on what the separation really buys us.

I agree with this for System.IO.FileSystem. I think merging it into System.Runtime.Extensions would  be pretty reasonable to me. (Note that there is a ton of dead code and unnecessary abstraction in System.IO.FileSystem right now. It won't look as bad as it looks once it is cleaned up.)

I think the reflection call for working set is ok. However, it can be written in more compact way now that the classic reflection APIs are back.

**Comment by ViktorHofer** [comment]
@jkotas looking into http://tempcoverage.blob.core.windows.net/report2/System.IO.FileSystem.diff.html it seems that S.IO.FileSystem does not have that much dead code. I can't say anything about the abstractions though. +1 for merging it down.

Isn't there another way for dealing with Process.WorkingSet? Reflection sounds like the last resort...

**Comment by JeremyKuhne** [comment]
There is a good chance the FileSystem abstractions won't be needed. I've intentionally dragged my feet on aggressively removing them pending potential WinRT changes around brokering.

**Comment by jkotas** [comment]
> Isn't there another way for dealing with Process.WorkingSet? Reflection sounds like the last resort...

You can always create a duplicate the code, or move the code down in the stack (with all its dependencies). For the Process.WorkingSet case, it is worse option than using reflection, I think.

Process.WorkingSet is not the only place where we use reflection to workaround the layering issues. For example, the stack trace dumping code in CoreLib is loading System.Reflection.Metadata using reflection.

**Comment by stephentoub** [comment]
At this point I don't think there's any proactive work to be done here.  We can re-open this if we discover otherwise.
