### ISSUE TITLE
[Impl] DCS/DCJS to Support new Serialization APIs Added in System.Runtime (e.g. ISerializable)

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#11477]
https://github.com/dotnet/corefx/commit/90be35920b48820536b8740f64d565ded55d811e added some serialization APIs in System.Runtime. DCS/DCJS should support these APIs.
- [x] System.NonSerializedAttribute (tracked by https://github.com/dotnet/corefx/issues/13367)
- [x] System.SerializableAttribute 
- [x] System.Runtime.Serialization.OptionalFieldAttribute  (tracked by https://github.com/dotnet/corefx/issues/13367)
- [x] System.Runtime.Serialization.IDeserializationCallback (tracked by https://github.com/dotnet/corefx/issues/13368)
- [x] System.Runtime.Serialization.IFormatterConverter 
- [x] System.Runtime.Serialization.ISerializable 
- [x] System.Runtime.Serialization.SerializationEntry 
- [x] System.Runtime.Serialization.SerializationInfo 
- [x] System.Runtime.Serialization.SerializationInfoEnumerator

**Comment by danmosemsft** [comment]
@shmao are these API's defined in Standard? If not (ie this issue is nice to have) then please remove the netstandard2.0 label.

**Comment by shmao** [comment]
@danmosemsft yes, the APIs are in NetStandard2.0.

**Comment by danmosemsft** [comment]
Ah ok. It was the 'if needed' that confused me.

**Comment by shmao** [comment]
All items have been done or tracked by separate issues. Closing this.
