### ISSUE TITLE
Port some missing miscellaneous types/members

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#11808]
~~\- [ ] T:System.Configuration.Assemblies.AssemblyHash~~
edit: Removed AssemblyHash from netstandard.

~~T:System.Configuration.Assemblies.AssemblyHashAlgorithm~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.MD5 .~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.None~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA1~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA384~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA512~~
~~F:System.Configuration.Assemblies.AssemblyHashAlgorithm.value__~~

~~T:System.Configuration.Assemblies.AssemblyVersionCompatibility~~
~~F:System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain~~
~~F:System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine~~
~~F:System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess~~
~~F:System.Configuration.Assemblies.AssemblyVersionCompatibility.value__~~
- [x] M:System.Diagnostics.DebuggableAttribute.#ctor(System.Boolean,System.Boolean)
- [x]  M:System.Diagnostics.DebuggableAttribute.get_DebuggingFlags
- [x] M:System.Diagnostics.DebuggableAttribute.get_IsJITOptimizerDisabled
- [x] M:System.Diagnostics.DebuggableAttribute.get_IsJITTrackingEnabled
- [x] F:System.Runtime.InteropServices.CharSet.Auto
- [x] F:System.Runtime.InteropServices.CharSet.None

~~T:System.Runtime.InteropServices.ExternalException~~
~~M:System.Runtime.InteropServices.ExternalException.#ctor~~
~~M:System.Runtime.InteropServices.ExternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~M:System.Runtime.InteropServices.ExternalException.#ctor(System.String)~~
~~M:System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Exception)~~
~~M:System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Int32)~~
~~M:System.Runtime.InteropServices.ExternalException.get_ErrorCode~~
~~M:System.Runtime.InteropServices.SafeHandle.Close~~
- [x] M:System.Runtime.InteropServices.StructLayoutAttribute.#ctor(System.Int16)

~~M:System.Reflection.AssemblyName.OnDeserialization(System.Object)~~
~~M:System.Reflection.CustomAttributeFormatException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
- [x] M:System.Reflection.StrongNameKeyPair.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
- [x] M:System.Reflection.StrongNameKeyPair.PublicKey
  ~~System.Runtime.Serialization.IDeserializationCallback.OnDeserialization(System.Object)~~

~~M:System.Reflection.TargetException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~

~~T:System.Runtime.Serialization.IObjectReference~~
- [ ] T:System.Runtime.Serialization.ISafeSerializationData
  ~~T:System.Runtime.Serialization.OptionalFieldAttribute~~
- [ ] T:System.Runtime.Serialization.SafeSerializationEventArgs

~~M:System.Security.VerificationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~M:System.TypeAccessException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~M:System.TypeLoadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
~~M:System.WeakReference.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)~~
- [x] T:System.Runtime.InteropServices.RuntimeEnvironment
- [x] M:System.Runtime.InteropServices.RuntimeEnvironment.#ctor
- [x] M:System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
- [x] M:System.Runtime.InteropServices.RuntimeEnvironment.get_SystemConfigurationFile
- [x] M:System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
- [x] M:System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
- [x] P:System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile

Removed form netstandard2.0 : https://github.com/dotnet/standard/commit/455687a1c8f86a54fbd7da4f056333290411021c
~~\- [ ] T:System.RuntimeArgumentHandle~~

The following types were removed from netstandard2.0 https://github.com/dotnet/standard/commit/e3e48e4e1e396381807eb255cf1f2150e73ce430.
~~T:System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMetadata~~
~~E:System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMetadata.DesignerNamespaceResolve~~
~~E:System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMetadata.ReflectionOnlyNamespaceResolve~~

Add tests for
- [ ] MemoryFailPoint

**Comment by kouvel** [comment]
Added System.Runtime.InteropServices.RuntimeEnvironment to the list

**Comment by danmosemsft** [comment]
This empty struct seems to fit best in this issue. It literally is an empty struct.

`T:System.RuntimeArgumentHandle`

**Comment by kouvel** [comment]
Looks like there are more members of StrongNameKeyPair that should be included in this as well. From ns2.0:

```c#
    public partial class StrongNameKeyPair : System.Runtime.Serialization.IDeserializationCallback, System.Runtime.Serialization.ISerializable
    {
        public StrongNameKeyPair(byte[] keyPairArray) { }
        public StrongNameKeyPair(System.IO.FileStream keyPairFile) { }
        protected StrongNameKeyPair(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
        public StrongNameKeyPair(string keyPairContainer) { }
        public byte[] PublicKey { get { throw null; } }
        void System.Runtime.Serialization.IDeserializationCallback.OnDeserialization(object sender) { }
        void System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
    }
```

**Comment by ramarag** [comment]
For now i am striking some methods of as they depend on crypto and there is no straightforward implementations, will revisit them if they are indeed used/usefult
 public partial class StrongNameKeyPair : System.Runtime.Serialization.IDeserializationCallback, System.Runtime.Serialization.ISerializable
    
public StrongNameKeyPair(byte[] keyPairArray) { }
~~public StrongNameKeyPair(System.IO.FileStream keyPairFile) { }~~
        protected StrongNameKeyPair(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
~~public StrongNameKeyPair(string keyPairContainer) { }~~
 ~~public byte[] PublicKey { get { throw null; } }~~
        void System.Runtime.Serialization.IDeserializationCallback.OnDeserialization(object sender) { }
        void System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }

**Comment by danmosemsft** [comment]
@ramarag I see your comment above about striking out some parts of StringNameKeyPair. Anything we don't implement must be present, it can throw PlatformNotSupportedException if forced.

I see this one is still missing.
```
   public class StrongNameKeyPair : IDeserializationCallback, ISerializable {
        public StrongNameKeyPair(FileStream keyPairFile);
    }
```

Do you need a new issue for this?

**Comment by kouvel** [comment]
I'll take a look
