### ISSUE TITLE
Tracking targeting uap101aot

### ISSUE THREAD

**Issue by SedarG** [dotnet/corefx#12013]
[See the discussion in #12004 for more context]

Below is the list of libraries that explicitly target netcore50aot. It's a helpful list to look out as these libs are likely going to need to target uap101aot explicitly. Note, however, that it's not **the** list of libs that we need to work on and do the changes to explicitly target uap10.1. Some of the libs in this list will not have any change so it's OK to leave them as is. And there might be other libs that requires support from the CoreLib layer, which will be an addition to this list. Still, this is a list to start with
- [x] System.Collections
- [ ] System.Diagnostics.Tools
- [ ] System.Diagnostics.Tracing
- [x] ~~System.Globalization.Calendars~~ (This package is a pure façade. no need to update it for uap10.1)
- [x] System.Globalization
- [x] System.IO
- [x] System.Reflection
- [x] System.Reflection.Primitives
- [x] System.Resources.ResourceManager
- [x] System.Runtime.Handles
- [ ] System.Runtime.InteropServices
- [x] System.Runtime
- [x] ~~System.Text.Encoding.Extensions~~ (This package is a pure façade. no need to update it for uap10.1)
- [x] ~~System.Text.Encoding~~  (This package is a pure façade. no need to update it for uap10.1)
- [x] System.Threading.Tasks
- [x] System.Threading.Timer
- [ ] System.Diagnostics.Debug
- [ ] System.Runtime.Extensions
- [x] System.Private.Uri
- [x] ~~System.AppContext~~ (This library doesn't have anything new. no need to cross compile it for uap10.1)
- [x] ~~System.Diagnostics.Contracts~~ (This package is a pure façade. no need to update it for uap10.1)
- [x] System.Diagnostics.StackTrace
- [ ] System.Dynamic.Runtime
- [ ] System.Linq.Expressions
- [x] ~~System.Private.DataContractSerialization~~ (This library doesn't have anything new. no need to cross compile it for uap10.1)
- [x] ~~System.Reflection.DispatchProxy~~ (This package is a pure façade for netcore50aot. no need to update it for uap10.1)
- [x] System.Reflection.Extensions
- [x] System.Reflection.TypeExtensions
- [x] ~~System.Runtime.InteropServices.RuntimeInformation~~ (This library doesn't have anything new. no need to cross compile it for uap10.1)
- [x] System.Runtime.InteropServices.WindowsRuntime
- [x] System.Runtime.Serialization.Primitives
- [ ] System.Threading
- [ ] System.Xml.XmlSerializer
- [ ] System.IO.IsolatedStorage

**Comment by SedarG** [comment]
Related: #11551

**Comment by danmosemsft** [comment]
@joperezr is there any value in this issue now or can it be closed?

**Comment by joperezr** [comment]
I would base myself more on actual apicompat baselines to see what we are missing as opposed to this issue since types have moved around so stuff that needed a configuration before might not need it now or vice versa. So I guess it's fine to close for now.
