### ISSUE TITLE
Review types for Serialization test coverage

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#15731]
The binary rewriter that currently strips S.P.CoreLib.dll turns out to have been removing _some_ instances of serialization infrastructure on types it retained. That implies that we don't have test coverage for binary serializing these.

Investigate, and add coverage if necessary. If the type is internal to S.P.CoreLib.dll and is not serialized indirectly then possibly it isn't necessary. If the type is missing [Serializable] on it, it's also not necessary.

What I grepped for
```
[OnDeserialized]
[OnSerializing]
[OnSerialized]
serialization constructor or other function passed SerializationInfo
```

Types affected were in

- [ ] mscorlib/src/System/Globalization/SortKey.cs
- [ ] mscorlib/src/System/Security/Util/TokenBasedSet.cs
- [ ] mscorlib/src/System/Security/Util/URLString.cs
- [ ] mscorlib/src/System/Security/PermissionSet.cs (PermissionSet)
- [ ] mscorlib/src/System/Text/*Encoding.cs
- [ ] mscorlib/src/System/AppDomainUnloadedException.cs
- [ ] mscorlib/src/System/Collections/Comparer.cs
- [ ] mscorlib/src/System/Collections/Generic/Comparer.cs (several classes)
- [ ] mscorlib/src/System/Collections/Hashtable.cs (the internal hashtable)
- [ ] mscorlib/src/System/IO/DriveNotFoundException.cs
- [ ] mscorlib/src/System/InsufficientMemoryException.cs
- [ ] mscorlib/src/System/OperatingSystem.cs
- [ ] mscorlib/src/System/Reflection/ConstructorInfo.cs
- [ ] mscorlib/src/System/Runtime/CompilerServices/RuntimeWrappedException.cs
- [ ] mscorlib/src/System/Runtime/Serialization/FormatterServices.cs - SurrogateForCyclicalReference
- [ ] mscorlib/src/System/Runtime/Serialization/ISurrogateSelector.cs
- [ ] mscorlib/src/System/Text/DecoderNLS.cs

@stephentoub  fyi.

**Comment by karelz** [comment]
@tarekgh this is not Serialization itself, rather a property of CoreFX code base around serialization of specific types, right? In that case it should be in area-Meta.

**Comment by tarekgh** [comment]
@karelz this is related to serialization only. I understand it is not changing anything in the serialization engine but it has nothing to do with anything else but serialization. isn't better we can be more specific about that?

**Comment by karelz** [comment]
We could be specific in CoreFX (check with @danmosemsft).
We should not ask Serialization team to fix our types to be correctly serializable though. That's not their key focus. If we have questions, they can help.

**Comment by tarekgh** [comment]
marking it as serialization doesn't mean we are asking the serialization team to do the work. but anyway, if it is up to me I would keep it serialization area.

**Comment by karelz** [comment]
Here's how I think about it:
Areas are associated with API contracts - as in implementation of them. Meta and Infrastructure are 2 exceptions to that rule. And Serialization is a merge of couple of serialization-related types. So 3 exceptions altogether :)

Applying serialization attributes does not require Serialization area expertise, so it does not belong here.
Same would apply for "Replace all/most List<T> usages with ArrayList<T> in code in CoreFX" - it belongs into Meta (cross-cutting), not under Collections where the types live.
Makes sense?
I will be happy to follow up offline - I think it is good to get on the same page. I tried to capture it in [areas](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) description - feel free to suggest clarifications there.

**Comment by tarekgh** [comment]
I am fine with your marking

**Comment by ViktorHofer** [comment]
@danmosemsft is this fixed now?
