### ISSUE TITLE
Use TryAdd throughout corefx

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#17034]
Now that https://github.com/dotnet/corefx/issues/1942 has been exposed, we can replace all of the places using

```cs
if (!dictionary.ContainsKey(key))
{
    dictionary.Add(key, value);
}
```

with

```cs
if (dictionary.TryAdd(key, value))
{
}
```

and get better perf for free.

Not sure if there will be any issues with targeting a framework that doesn't have the API, but IIRC @weshaggard said that everything is being built against netcoreapp now so everywhere in corefx should have the API write away.

**Comment by danmosemsft** [comment]
I found only these with a simple regex.
`if +\( *![a-zA-Z]+.ContainsKey\( *[a-zA-Z]+ *\) *\) *\n? *{ *\n? *[a-zA-Z]+.Add`

```c#
C:\git\corefx\src\System.Linq.Expressions\src\System\Linq\Expressions\Interpreter\LightCompiler.cs:
 1636:                     if (!caseDict.ContainsKey(key))
 1637:                     {
 1638:                         caseDict.Add(key, caseOffset);
 1690:                     else if (!caseDict.ContainsKey(key))
 1691:                     {
 1692:                         caseDict.Add(key, caseOffset);

C:\git\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlNodeReader.cs:
 1023:                                 if (!dict.ContainsKey(localName))
 1024:                                 {
 1025:                                     dict.Add(_nameTable.Add(localName), _nameTable.Add(a.Value));

C:\git\corefx\src\System.Private.Xml\src\System\Xml\Xsl\XsltOld\XsltCompileContext.cs:
  274:                     if (!documents.ContainsKey(uri))
  275:                     {
  276:                         documents.Add(uri, null);

C:\git\corefx\src\System.Private.Xml.Linq\src\System\Xml\Schema\XNodeValidator.cs:
  156:                 if (!schemaInfos.ContainsKey(si))
  157:                 {
  158:                     schemaInfos.Add(si, si);
```

**Comment by danmosemsft** [comment]
It should be possible to use it anywhere -- our build should fail if I'm wrong. Do you want ot take a shot?

**Comment by karelz** [comment]
@jamesqo while everything is built on netcoreapp, some libraries in CoreFX target earlier .NET Standard and some cross-compile to Desktop as well. Make sure you don't break those.

**Comment by jamesqo** [comment]
@danmosemsft There appear to be some that you have missed, e.g. [here](https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L1746-L1774), [here](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/System/CodeDom/CodeNamespaceImportCollection.cs#L34). I'm betting that there are a lot more cases in [this grep](https://gist.github.com/jamesqo/7b71a0f1a1450d84d189a50c5b740a97) for `if.*\!.*ContainsKey` that were not picked up by your regex.

**Comment by danmosemsft** [comment]
Right -- and another 10-15 in Corelib. 

Now we just need a volunteer to plow through some of these.

**Comment by rionmonster** [comment]
I started working on this a short while ago and had a few questions:

- Should the replacement be performed within the existing `src` projects only or do we want to target the `tests` as well?
- In a few scenarios, I've had the `TryAdd()` method not recognized on a given Dictionary object (i.e. not recognized by autocompletion and won't build). Is this the expected behavior for those that "won't" be replaced with the new call? One example is [found in System.CodeDom\NamespaceImportCollection.cs](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/System/CodeDom/CodeNamespaceImportCollection.cs#L32-L39).

**Comment by danmosemsft** [comment]
Yes, it would make sense to update tests as well.

@joperezr can you think of a reason why this API wouldn't be visible someplace? Everyone should see this API, it's on corelib?

**Comment by danmosemsft** [comment]
@karelz what magic does @rionmonster need to do to get assigned this issue..

**Comment by karelz** [comment]
@rionmonster ping me when you accept collaboration invite, I can then assign it to you.

**Comment by rionmonster** [comment]
@karelz 

Done.

I'm compiling a list of all of the non-test areas where changes are being made as well as those that aren't working but should possibly me (i.e. where the `TryAdd()` method is unrecognized).

This should be a fairly thorough list as well, as I am going around checking everything with a `ContainsKey()` to ensure that some expression, grep, or other search didn't miss anything. I'll start with these and go back and handle the tests afterwards.

**Comment by rionmonster** [comment]
Alright, here's the list, which should include all non-test related changes from `Dictionary.ContainsKey()` to `Dictionary.TryAdd()` that follows the pattern indicated earlier.

**System.CodeDom**
- [ ]	...\src\System\CodeDom\CodeNamespaceImportCollection.cs(34)

**System.ComponentModel.TypeConverter**
- [X] ...\src\System\ComponentModel\ReflectTypeDescriptionProvider.cs(451)
- [X]	...\src\System\ComponentModel\ReflectTypeDescriptionProvider.cs(489)

**System.Data.Common**
- [X]	...\src\System\Data\DataView.cs(1333)
- [X] ...\src\System\Data\Common\AdapterUtil.cs(1185)	

**System.Data.SqlClient**
- [ ] ...\src\System\Data\Common\AdapterUtil.cs(976) 
- [ ] ...\src\System\Data\SqlClient\SNI\SNIMarsConnection.cs(241) 

**System.Diagnostics**
- [ ] ...\src\System\Diagnostics\Tracing\EventSource.cs(6272)

**System.DirectoryServices.AccountManagement**
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(326) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(343) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(505) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(523) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(682) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADDNLinkedAttrSet.cs(810) 
- [ ] ...\src\System\DirectoryServices\AccountManagement\AD\ADStoreCtx_Query.cs(1178)

**System.IO.Compression**
- [ ]	...\src\System\IO\Compression\ZipArchive.cs(368)

**System.Linq.Expressions**
- [X]	...\src\System\Linq\Expressions\Compiler\BoundConstants.cs(87)
- [X]	...\src\System\Linq\Expressions\Interpreter\LightCompiler.cs(1636)
- [X]	...\src\System\Linq\Expressions\Interpreter\LightCompiler.cs(1690)

**System.Net.NetworkInformation**
- [ ]	...\src\System\Net\NetworkInformation\NetworkAddressChange.Windows.cs(104) 
- [ ]	...\src\System\Net\NetworkInformation\NetworkAddressChange.Windows.cs(225) 

**System.Private.DataContractSerialization**
- [X]	...\src\System\Runtime\Serialization\DataContract.cs(2109)	
- [X]	...\src\System\Runtime\Serialization\HybridObjectCache.cs(45)
- [X]	...\src\System\Runtime\Serialization\Json\JsonDataContract.cs(293)
- [X]	...\src\System\Runtime\Serialization\Json\JsonDataContract.cs(302)

**System.Private.Xml**
- [ ]	...\src\System\Xml\Dom\DocumentSchemaValidator.cs(195) 
- [ ]	...\src\System\Xml\Dom\DocumentSchemaValidator.cs(203) 
- [ ]	...\src\System\Xml\Dom\XmlNodeReader.cs(1015) 
- [ ]	...\src\System\Xml\Dom\XmlNodeReader.cs(1023) 
- [ ]	...\src\System\Xml\Schema\DtdParser.cs(1437) 
- [ ]	...\src\System\Xml\Schema\DtdParser.cs(1444) 
- [ ]	...\src\System\Xml\Schema\DtdParserAsync.cs(1033) 
- [ ]	...\src\System\Xml\Schema\DtdParserAsync.cs(1040) 
- [ ]	...\src\System\Xml\Schema\DtdParserAsync.cs(1124) 
- [ ]	...\src\System\Xml\Schema\SchemaCollectionCompiler.cs(292) 
- [ ]	...\src\System\Xml\Schema\SchemaCollectionCompiler.cs(772) 
- [ ]	...\src\System\Xml\Schema\SchemaCollectionCompiler.cs(779) 
- [ ]	...\src\System\Xml\Schema\SchemaInfo.cs(356) 
- [ ]	...\src\System\Xml\Schema\SchemaInfo.cs(364) 
- [ ]	...\src\System\Xml\Schema\SchemaInfo.cs(371) 
- [ ]	...\src\System\Xml\Schema\SchemaInfo.cs(378) 
- [ ]	...\src\System\Xml\Schema\SchemaInfo.cs(385) 
- [ ]	...\src\System\Xml\Schema\SchemaSetCompiler.cs(158) 
- [ ]	...\src\System\Xml\Schema\SchemaSetCompiler.cs(842) 
- [ ]	...\src\System\Xml\Schema\XdrBuilder.cs(1052) 
- [ ]	...\src\System\Xml\Schema\XmlSchema.cs(210)
- [ ]	...\src\System\Xml\Serialization\Compilation.cs(304) 
- [ ]	...\src\System\Xml\Xsl\IlGen\StaticDataManager.cs(30) 
- [ ]	...\src\System\Xml\Xsl\Xslt\Compiler.cs(104) 
- [ ]	...\src\System\Xml\Xsl\Xslt\Compiler.cs(172) 
- [ ]	...\src\System\Xml\Xsl\XsltOld\XsltCompileContext.cs(274) 
- [ ]	...\tests\XmlSchema\XmlSchemaValidatorApi\ExceptionVerifier.cs(174) 
- [ ]	...\tests\Xslt\XslTransformApi\ExceptionVerifier.cs(174) 

**System.Private.Xml.Linq**
- [ ]	...\src\System\Xml\Schema\XNodeValidator.cs(156) 

**System.Reflection.Metadata**
- [ ]	...\src\System\Reflection\Metadata\Internal\NamespaceCache.cs(406) 

**System.Runtime.Serialization**
- [X]	...\src\System\Runtime\Serialization\SerializationObjectManager.cs(30)

**System.Security.AccessControl**
- [ ]	...\src\System\Security\AccessControl\Privilege.cs(150)
 
**System.ServiceProcess.ServiceController**
- [ ]  ...\src\System\ServiceProcess\ServiceController.cs(274) 
- [ ]  ...\src\System\ServiceProcess\ServiceController.cs(280) 

Everything that has been checked off was implemented without issues, however all of those unchecked items indicate that the `TryAdd()` method wasn't recognized (and any attempts to build using it would fail).

**Comment by danmosemsft** [comment]
@rionmonster great, you might start a PR with the ones you've done so far, then we can take a first look while we solve the other issue.

**Comment by danmosemsft** [comment]
@rionmonster one thing you might look at is code coverage -- make sure each of the points you change already have some test (otherwise we might want to add a test, or at least take more care)

You can see code coverage here
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

Optionally after yo'ure done someone could also update corelib. https://github.com/dotnet/coreclr/tree/master/src/mscorlib

**Comment by rionmonster** [comment]
@danmosemsft 

Sure thing. I'll push that one out shortly. 

Since we are doing tests as well, it may be best to update as many of these non-test calls prior to changing the actual tests themselves, just to be on the safe side. Coincidentally, the first applicable test that came up for a replacement was one of the performance dictionary tests (from `Performance\Perf.Dictionary.cs` in System.Collections), which is why I wanted possibly consider handling those after some of the other stuff is done.

There are plenty of tests that will need changing, I'm going through and making a list of those as well, just to make it easier to run though later (and it might serve some use to triage which to do, which to write, etc.).

**Comment by danmosemsft** [comment]
Yes, I would certainly run "old tests" against "new code". One way to do that is push up your implementation changes in your PR and make sure the CI system gets green. Then push up your test changes and CI can run again. They don't actually need to be in distinct commits in master.

**Comment by rionmonster** [comment]
@danmosemsft 

A quick comparison with all of the methods that have been changed thus far with the code coverage that you mentioned earlier indicates that all of the methods that are being tested should be covered and not require any new tests.

Additionally, my local build with these changes ran all of the available tests and passed without issue (and it looks like CI did as well).

**Comment by rionmonster** [comment]
As far as updating non-dictionary tests goes, there really were not too many and a pull request for these will be coming shortly:

**System.Data.SqlClient**
- [X] ...\tests\ManualTests\SQL\Common\InternalConnectionWrapper.cs(160)

**System.Linq.Expressions**
- [X] ...\tests\ILReader\ILPrinter.cs(123)

**System.Private.Xml.Linq**
- [X] ...\tests\TreeManipulation\XAttributeEnumRemove.cs(248)
- [X] ...\tests\TreeManipulation\XNodeSequenceRemove.cs(738)
- [X] ...\tests\xNodeBuilder\XmlReaderDiff.cs(42)

There were a bevy of `ContainsKey()` calls scattered across all of the different dictionary flavors (i.e. `SortedDictionary`, `ImmutableDictionary`, `ReadOnlyDictionary`, `ConcurrentDictionary`, etc.) but I figured I would leave those for last, if we wanted to touch them at all.

One thing worth noting, I was able to use the `TryAdd()` method within some of the tests of assemblies that I couldn't use it for normally. One example of this would be the `System.Private.Xml.Linq`, which did not recognize the method, however I updated several test cases that allowed it just fine.

**Comment by danmosemsft** [comment]
Hey @joperezr can you suggest why @rionmonster can't see this API from some libraries? It's in corelib and exposed through System.Runtime, that's visible to everyone right?

**Comment by danmosemsft** [comment]
> There were a bevy of ContainsKey() calls scattered across all of the different dictionary flavors (i.e. SortedDictionary, ImmutableDictionary, ReadOnlyDictionary, ConcurrentDictionary, etc.) but I figured I would leave those for last, if we wanted to touch them at all.

Not sure what you're asking. We can't add the same API to those types without going through API proposal/review process for them. Of course anything deriving from Dictionary get it for free but those don't. If you mean is there more to replace there I think most or all of their use of ContainsKey() will not be a pattern you can replace.

**Comment by rionmonster** [comment]
I just didn't want to break any of the existing tests, but I didn't go through each of those too rigorously thus far. As you mentioned, it's unlikely that that pattern will pop up too often, so the replacement shouldn't be too bad.

I'll update the PR to include those updated tests, once I get them done.

**Comment by rionmonster** [comment]
Just pushed up the PR, it turns out there was only a single test case that matched that pattern (and wasn't a test to explicitly test the `ContainsKey()` method).

**Comment by rionmonster** [comment]
As far as the tests go, these are all of the Dictionary-related ones that could potentially benefit from the change:

**System.Collections**
- [ ]  ...\src\Common\tests\System\Collections\IDictionary.Generic.Tests.cs(769)
  _[IDictionary_Generic_RemoveKey_DefaultKeyContainedInDictionary]_
- [ ]  ...\src\Common\tests\System\Collections\IDictionary.Generic.Tests.cs(800)
  _[IDictionary_Generic_TryGetValue_ValidKeyContainedInDictionary]_
- [ ]  ...\src\Common\tests\System\Collections\IDictionary.Generic.Tests.cs(836)
  _[IDictionary_Generic_TryGetValue_DefaultKeyContainedInDictionary]_
- [ ]  ...\src\System.Collections\tests\Generic\SortedList\SortedList.Generic.Tests.cs(410)
  _[SortedList_Generic_RemoveAt_NonDefaultValueContainedInCollection]_
- [X]  ...\src\System.Collections\tests\Performance\Perf.Dictionary.cs(23)

Those within the generic tests didn't seem to like it, but that should cover everything.

**Comment by danmosemsft** [comment]
If you have any doubt it is fine to do a followup PR just for the test changes. If you want to do that you could break them into another branch and force push to your PR so it just has product changes.

**Comment by joperezr** [comment]
> Hey @joperezr can you suggest why @rionmonster can't see this API from some libraries? It's in corelib and exposed through System.Runtime, that's visible to everyone right?

The problem of not seeing this API will be when building with the configuration of netstandard. The reason is that this particular API is currently only available in uap and netcoreapp, and if we want to expose it in netstandard then we would have to add it to the dotnet/standard repo (cc. @weshaggard). 

@jamesqo responding to what you said earlier here:
> Not sure if there will be any issues with targeting a framework that doesn't have the API, but IIRC @weshaggard said that everything is being built against netcoreapp now so everywhere in corefx should have the API write away.

That is not the case anymore. If we have something building as netstandard, then it will actually build against the reference assemblies that get restored from the NETStandard.Library package that gets produced in the dotnet/standard repo. It did use to be the case that everything was netcoreapp, but that has been fixed.

**Comment by karelz** [comment]
We cannot add the API into netstandard, unless it is present on all the platforms .NET Standard is supposed to cover (.NET 4.6.1)

**Comment by danmosemsft** [comment]
@rionmonster to summarize what @joperezr says above (and I should have known) some of our libraries are built in a configuration called netstandard that cannot access API that's not in netstandard (like this one). They could be changed in some cases to not do that, but use of this API is not a good enough reason. In short: just use where you can.

**Comment by rionmonster** [comment]
I figured that would be the case based on some of the earlier conversation. Given that, I believe that the current pull request has added it just about everywhere that it is reasonable to be included (both source and tests). 

I may need to revert one of the recently changed dictionary performance tests however, as it seemed to break the "Vertical Netfx Build" with the following error:

> error CS1061: 'Dictionary' does not contain a definition for 'TryAdd' and no extension method 'TryAdd' accepting a first argument of type 'Dictionary' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\netfx_debug_p---88b09898\src\System.Collections\tests\Performance\System.Collections.Performance.Tests.csproj]

I'm not sure if this is intentional or not, as the tooling in Visual Studio recognized and exposed the `TryAdd()` method, but it seems when it was built in CI that it didn't appear to like it very much. The test in question [can be found here](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Performance/Perf.Dictionary.cs#L16-L27), but I just need to know if this one needs to be reverted or if some other action needs to be taken.

**Comment by rionmonster** [comment]
Is there anything else that needs to be done related to this? The PR has been merged. I didn't know if the issue was staying open for housekeeping reasons or if it had just been passed over.

Also - will any potential changes related to this need to be added into the CoreCLR repo?

**Comment by danmosemsft** [comment]
I think we just overlooked it. If you put the text "fixes #nnnn" in the PR then github closes the issue for you.

For your 2nd question -- I didn't personally look but I don't think I saw a PR yet that uses it in coreclr (in corelib). You'd be welcome if you're interested, although at the moment mainly focusing on 2.0 stuff per https://github.com/dotnet/corefx/issues/17619
