### ISSUE TITLE
Review "dead" code (not getting compiled)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#17866]
None of these are getting compiled. All either need deleting, or hooking up to the build , as appropriate.
(I've either opened issues or put up PR's for all the other dead files I found)

- [ ] Common/tests/System/Net/Sockets/Performance/SocketTestClientAPM.cs
- [ ] System.CodeDom/src/System/CodeDom/Compiler/CompilerParameters.Evidence.cs
- [ ] System.CodeDom/src/System/CodeDom/Compiler/CompilerResults.Evidence.cs
- [ ] System.Data.Common/src/System/Data/Common/DbProviderFactory.CreatePermission.cs
- [x] System.Data.SqlClient/tests/Tools/TDS/TDS/TDSPacketTokenType.cs
- [x] System.Data.SqlClient/tests/Tools/TDS/TDS/TDSPacketType.cs
- [ ] System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/CertificateCollectionDeltas.cs
- [ ] System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/ValueList.cs
- [ ] System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/ValueListEnumerator.cs
- [ ] System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/config.cs
- [ ] System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/testobj.cs
- [ ] System.DirectoryServices.AccountManagement/tests/testobj.cs
- [ ] System.DirectoryServices/src/System/DirectoryServices/DirectoryDescriptionAttribute.cs
- [ ] System.Net.Http/tests/FunctionalTests/prerequisites/BasicAuthModule.cs
- [ ] System.Net.Sockets/tests/PerformanceTests/SocketPerformanceAPMTests.cs
- [ ] System.Net.WebSockets/tests/WebSocketExceptionTests.netstandard17.cs
- [x] System.Runtime.Extensions/src/System/IO/Path.Win32.cs
- [ ] System.Runtime.Numerics/tests/BigInteger/add.cs
- [ ] System.Runtime.WindowsRuntime/src/System/IO/IsolatedStorage/IsolatedStorageFileIOHelper.cs
- [ ] System.Runtime/tests/Common/CompareHelper.cs
- [ ] System.Runtime/tests/Performance/Perf.Array.cs
- [ ] System.Runtime/tests/netstandard.1.7.Tests.cs
- [ ] System.Security.AccessControl/tests/CommonSecurityDescriptor/CommonSecurityDescriptor_CreateFromBinaryForm.cs
- [ ] System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/IncrementalHash.net46.cs

**Comment by Clockwork-Muse** [comment]
Also /System.Threading.Tasks/tests/Task/TaskFromAsyncTest2.cs

Although given the state of some of those tests...

**Comment by stephentoub** [comment]
> None of these are getting compiled

Some of these (e.g. the `*.Evidence.cs` ones) were added by the Mono folks to be used in their builds.

**Comment by EgorBo** [comment]
`*.Evidence`, `*.CreatePermission.cs` were added by us for mono, indeed, probably we should rename them to `*.Mono.cs` @marek-safar

**Comment by marek-safar** [comment]
We need to add mono files to mono configuration build but I think this configuration is still not included in CoreFX CI

**Comment by stephentoub** [comment]
This is over two years old now and is out-of-date, so I'm going to close it.  Please open a new issue with updated details if desired.
