### ISSUE TITLE
Review Open TODOs around the entire code base

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#19235]
Currently there are 2923 TODOs in the entire corefx code base. Below is the ordered grouping of TODOs by 1st level directories. As some of them can probably be ignored/removed, it's still worth giving them a look at some point of time.

## Areas with TODOs
- [ ] System.Private.Xml: 412
- [ ] System.Linq.Expressions: 356
- [ ] System.Net.Http: 294
- [ ] System.Net.Sockets: 282
- [ ] System.Data.Common: 144
- [ ] System.Net.WebSockets.Client: 132
- [ ] System.Reflection.Metadata: 116
- [ ] Microsoft.CSharp: 112
- [ ] System.Runtime.Extensions: 112
- [ ] System.Private.Xml.Linq: 110
- [ ] Common: 102
- [ ] Microsoft.VisualBasic: 90
- [ ] System.Runtime: 72
- [ ] System.Diagnostics.Tracing: 64
- [ ] System.Net.Http.WinHttpHandler: 62
- [ ] System.Data.SqlClient: 54
- [ ] System.Reflection.TypeExtensions: 34
- [ ] System.Private.DataContractSerialization: 26
- [ ] System.Runtime.Serialization.Formatters: 20
- [ ] System.IO.FileSystem: 18
- [ ] System.Numerics.Vectors: 18
- [ ] System.Data.Odbc: 16
- [ ] System.DirectoryServices.AccountManagement: 16
- [ ] System.Net.Requests: 16
- [ ] System.Runtime.Numerics: 16
- [ ] System.Net.Security: 14
- [ ] System.IO.Compression: 12
- [ ] System.DirectoryServices.Protocols: 10
- [ ] System.IO.Ports: 10
- [ ] System.Net.NameResolution: 10
- [ ] System.Private.Uri: 10
- [ ] Native: 8
- [ ] System.Diagnostics.StackTrace: 8
- [ ] System.Security.Principal.Windows: 8
- [ ] System.Transactions.Local: 8
- [ ] System.Collections.Concurrent: 6
- [ ] System.ComponentModel.Annotations: 6
- [ ] System.Diagnostics.DiagnosticSource: 6
- [ ] System.IO.Packaging: 6
- [ ] System.IO.Pipes: 6
- [ ] System.Memory: 6
- [ ] System.Net.HttpListener: 6
- [ ] System.Runtime.InteropServices: 6
- [ ] System.Security.Cryptography.X509Certificates: 6
- [ ] System.Security.Cryptography.Xml: 5
- [ ] Microsoft.Win32.Registry: 4
- [ ] System.Configuration.ConfigurationManager: 4
- [ ] System.DirectoryServices: 4
- [ ] System.Dynamic.Runtime: 4
- [ ] System.Linq: 4
- [ ] System.Threading.Tasks: 3
- [ ] shims: 2
- [ ] System.Collections: 2
- [ ] System.ComponentModel.TypeConverter: 2
- [ ] System.Console: 2
- [ ] System.IO.IsolatedStorage: 2
- [ ] System.IO.MemoryMappedFiles: 2
- [ ] System.IO.UnmanagedMemoryStream: 2
- [ ] System.Json: 2
- [ ] System.Linq.Queryable: 2
- [ ] System.Net.Ping: 2
- [ ] System.Net.ServicePoint: 2
- [ ] System.Net.WebClient: 2
- [ ] System.Net.WebProxy: 2
- [ ] System.Reflection.Emit: 2
- [ ] System.Resources.Writer: 2
- [ ] System.Runtime.WindowsRuntime: 2
- [ ] System.Threading: 2
- [ ] System.Threading.Tasks.Dataflow: 2
- [ ] System.Runtime.Serialization.Json: 1
- [ ] System.Security.AccessControl: 1
- [ ] System.Text.Encoding: 1
- [ ] System.Text.Encodings.Web: 1
- [ ] System.Threading.Tasks.Extensions: 1
- [ ] System.Threading.Tasks.Parallel: 1
- [ ] System.Threading.Thread: 1
- [ ] System.Xml.ReaderWriter: 1

`~\corefx\src>findstr /si /C:"TODO" *`
All TODOs: [todo.txt](https://github.com/dotnet/corefx/files/970965/todo.txt)

cc @karelz @stephentoub @danmosemsft

**Comment by ViktorHofer** [comment]
```
System.Private.Xml: 412
System.Linq.Expressions: 356
System.Net.Http: 294
System.Net.Sockets: 282
System.Data.Common: 144
System.Net.WebSockets.Client: 132
System.Reflection.Metadata: 116
Microsoft.CSharp: 112
System.Runtime.Extensions: 112
System.Private.Xml.Linq: 110
Common: 102
Microsoft.VisualBasic: 90
System.Runtime: 72
System.Diagnostics.Tracing: 64
System.Net.Http.WinHttpHandler: 62
System.Data.SqlClient: 54
System.Reflection.TypeExtensions: 34
System.Private.DataContractSerialization: 26
System.Runtime.Serialization.Formatters: 20
System.IO.FileSystem: 18
System.Numerics.Vectors: 18
System.Data.Odbc: 16
System.DirectoryServices.AccountManagement: 16
System.Net.Requests: 16
System.Runtime.Numerics: 16
System.Net.Security: 14
System.IO.Compression: 12
System.DirectoryServices.Protocols: 10
System.IO.Ports: 10
System.Net.NameResolution: 10
System.Private.Uri: 10
Native: 8
System.Diagnostics.StackTrace: 8
System.Security.Principal.Windows: 8
System.Transactions.Local: 8
System.Collections.Concurrent: 6
System.ComponentModel.Annotations: 6
System.Diagnostics.DiagnosticSource: 6
System.IO.Packaging: 6
System.IO.Pipes: 6
System.Memory: 6
System.Net.HttpListener: 6
System.Runtime.InteropServices: 6
System.Security.Cryptography.X509Certificates: 6
System.Security.Cryptography.Xml: 5
Microsoft.Win32.Registry: 4
System.Configuration.ConfigurationManager: 4
System.DirectoryServices: 4
System.Dynamic.Runtime: 4
System.Linq: 4
System.Threading.Tasks: 3
shims: 2
System.Collections: 2
System.ComponentModel.TypeConverter: 2
System.Console: 2
System.IO.IsolatedStorage: 2
System.IO.MemoryMappedFiles: 2
System.IO.UnmanagedMemoryStream: 2
System.Json: 2
System.Linq.Queryable: 2
System.Net.Ping: 2
System.Net.ServicePoint: 2
System.Net.WebClient: 2
System.Net.WebProxy: 2
System.Reflection.Emit: 2
System.Resources.Writer: 2
System.Runtime.WindowsRuntime: 2
System.Threading: 2
System.Threading.Tasks.Dataflow: 2
System.Runtime.Serialization.Json: 1
System.Security.AccessControl: 1
System.Text.Encoding: 1
System.Text.Encodings.Web: 1
System.Threading.Tasks.Extensions: 1
System.Threading.Tasks.Parallel: 1
System.Threading.Thread: 1
System.Xml.ReaderWriter: 1
```

**Comment by danmosemsft** [comment]
Thank you for kicking this off. We should not allow any new TODO's (or UNDONE's or BUGBUG's...) in the code, except perhaps in limited circumstances such as bringing up a new ported library. If something is worth a TODO, it's worth an issue. Ideally we would not have to do a pass like this.

**Comment by danmosemsft** [comment]
Actually looks much less worse than it seems. Most of these 2,900 are in tests (like `[OuterLoop] // TODO: Issue #11345`) or are bogus like "ToDouble".

Searching for capitalized TODO in product sources in CoreFX I see only 206. Looks like about half include an issue number.

**Comment by ViktorHofer** [comment]
Closing as I can't see any action on this item for now.
