### ISSUE TITLE
WinHttpHandler authentication behavior

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#20604]
- [ ] IsWindowsImplementation/IsNotWindowsImplementation is incorrect and prevents some of the tests from executing on certain platforms (see #20341 for a potential fix in GetContextHelper.cs).

- [ ] The following tests fail on both .Net Framework (on my machine) as well as on .Net Core (for details and a possible fix see #20341 and comments within that PR.) 

```NtlmAuthentication_Conversation_ReturnsExpectedType2Message
NtlmAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode
NegotiateAuthentication_Conversation_ReturnsExpectedType2Message
NegotiateAuthentication_InvalidRequestHeaders_ReturnsExpectedStatusCode
```
- [ ] After the fix proposed in #20341 some of the test variations are expected to fail due to a behavior difference in WinHTTP/Negotiate when connecting to localhost servers.

For more information also see #20096
