### ISSUE TITLE
Follow-up feedback/action items for WinHttpHandler

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#2165]
This issue is capturing feedback from the PR which copied the sources of WinHttpHandler into GitHub. 

https://github.com/dotnet/corefx/pull/2149

While most of the original feedback was addressed in the PR, some feedback action items are deferred and are being tracked in this issue.
- [x] Review use of SafeWinHttpHandle. Check for leaks etc. - Tracking with #2501
- [x] Review TODO's in code. - Done. All TODO's have separate issues.
- [x] Consolidate use of Safe*Handle code especially SafeHandleZeroOrMinusOneIsInvalid classes - Tracking with #2501
- [x] Optimize error handling around chain.Build(). - Done #4910
- [x] Optimize closures in Task related lambdas - Done #3867
- [x] Optimize use of TaskCompletionSource regarding `RequestState` - Done #3867
- [x] Propagate `CancellationToken` in calls to `TrySetCanceled`
  Fixed w/ #2608 
- [x] Pass `CancellationToken` to `CopyToAsync` - Considered but `HttpContent.CopyToAsync` does not have an overload that takes a `CancellationToken`.
- [x] Consider moving `HRESULT_FROM_WIN32` method to Common/Interop folder. - Done #2511
- [x] Consider change DLL import signature of `GetModuleHandle` to return `SafeHandle` or use `GetModuleEx` with `GET_MODULE_HANDLE_EX_FLAG_PIN` or `GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT` - Considered but there are no race conditions since the 'winhttp.dll' is always loaded during the use of the WinHttpHandler class.
- [x] Add UnitTests to test fix with proxy authentication and redirection for PR #2463
- [x] Move duplicate code in WinHttpCertificateHelper.cs and merge with similar code used in System.Net.Security - Tracked in #14542.
- [x] Optimize auth scheme lookups in WinHttpAuthHelper.cs - WON'T FIX.
- [x] Register callback on cancellation token to cancel WinHTTP operation for WinHttpRequestStream, WinHttpResponseStream - Issue #8627 for WinHttpResponseStream
- [x] Add logging for failures in classes such as WinHttpResponseParser, WinHttpResponseStream - Tracked in #7856.
- [x] Consider refactoring cache logic from WinHttpAuthHelper into separate class and avoid out parameters - WON'T FIX.
- [x] Optimize algorithm used in scanning client certificate list in WinHttpCertificateHelper - WON'T FIX.
- [x] Refactor cookie handling from WinHttpHandler into separate class. - Done #5001

**Comment by darrelmiller** [comment]
Would there be any possibility that the credential management/redirection handling/cookie management could be refactored into distinct message handlers that could be chained together?

I see a few benefits of this:
- The WinHttpHandler code itself gets simpler, easier to reason about and easier to debug
- If for some reason those components can't be moved out of WinHttpHandler it would be very useful to know why because it means there is something that we can't do further down the pipeline.  Maybe that could be resolved.
- There may be scenarios where we want to replace one of those components.   For example, from what I can tell, the auth mechanism does not have support for realms, and more concerning, I can't see where it takes the www-authenticate header into consideration.  Although, maybe that is in the WinHttp library and I just can't see that code.
- There is also some variability about how some people handle redirect requests.  Replacing that functionality would be useful.

I realize that this built in code can be disabled using policies, however, it would be really nice just to be able to pull the code completely out of the request/response pipeline.

**Comment by davidsh** [comment]
@darrelmiller WinHttpHandler was designed to be tightly coupled against the native Windows WinHTTP component.   In addition, many of the aspects you mentioned (credentials, cookies, redirection) are woven inside WinHTTP.   This design gives the maximum performance characteristics.   

Regarding your questions about the `www-authenticate` header, native WinHTTP supports the standard BASIC, DIGEST, NEGOTIATE schemes.  In addition, developers can also manually add 'Authorization' header to an outgoing request to deal with things like OAuth or other custom authentication patterns.

**Comment by SidharthNabar** [comment]
A small point to add to David's response - 

For changing the handling of redirect requests, developers can disable the automatic redirection policy property of WinHttpHandler and handle redirects themselves in an upstream handler.

Similar with Cookie management - developers can choose the cookie policy of "Use specified Cookie container" and then manage the cookie container themselves, instead of using the WinHTTP cookie handling code.

**Comment by karelz** [comment]
@davidsh please spin off separate issue(s) which are worth tracking and close this one.

**Comment by davidsh** [comment]
Closing this issue now since all items are either fixed or tracked separately.
