### ISSUE TITLE
Tracking HttpListenerResponseTests.Headers.cs disabled tests

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#22057]
These tests were originally tracked by 17462 (UAP related) but against .Net Core (non-UAP).

- [ ] AddHeader_LongName_ThrowsArgumentOutOfRangeException
- [ ] AppendHeader_LongName_ThrowsArgumentOutOfRangeException
- [ ] Headers_SetRestricted_ThrowsArgumentException
- [ ] Headers_SetLongName_ThrowsArgumentOutOfRangeException
- [ ] Headers_SetRequestHeader_ThrowsInvalidOperationException

**Comment by caesar1995** [comment]
dup of #18784

@davidsh

**Comment by caesar1995** [comment]
Sorry, I need to submit a PR to change the [ActiveIssue #] first.

**Comment by stephentoub** [comment]
Reverted #22977, so reopening.
