### ISSUE TITLE
Tracking System.Threading.Channels Remaining Cleanup

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#24823]
Tracking item for moving  [System.Threading.Tasks.Channels](https://github.com/dotnet/corefxlab/commit/a7da3bc0a7eba50c345b21296f036989e92f949a) to corefx.

Related #24174

**Comment by stephentoub** [comment]
From https://github.com/dotnet/corefx/pull/24881:
- [ ] Perf. Some simplifications were recently made to the code that should make various lock-free optimizations easier.
- [ ] Testing. The tests currently provide 99.6% line coverage and 98.4% branch coverage, but especially in a concurrent library that's far from the whole story. The tests also aren't the most organized and could benefit from some cleanup.
- [ ] Rationalization with the rest of corefx. A few files like the SPSCQueue type already exist in corefx and should be factored out into Common.
- [ ] Debugging. We should review the debugging views for the relevant types to make sure appropiate info is surfaced.
- [ ] APIs. We removed the ReadAsync method from ChannelReader, but I think we should add it back, at least as a base virtual and overridden in the UnbufferedChannel implementation.
- [ ] Misc: Further code review, subsequent fixes, addressing any additional feedback, etc.

**Comment by philippgille** [comment]
@joshfree: Your link to System.Threading.Tasks.Channels is broken (404)

**Comment by danmosemsft** [comment]
I am going to nominally estimate 15 given the data above of 1 week for perf, plus code review, stress testing, applying feedback and some other dialable items. Feel free to change.

**Comment by tarekgh** [comment]
For debug view, I am seeing the needed info on the channel is surfaced nicely. I am pasting the image of such view from VS. it is handy to access any object related to the channel (reader, writer, sync object,...etc.)

![image](https://user-images.githubusercontent.com/10833894/35591752-e824fd96-05bf-11e8-9af4-e485d3df77f4.png)

@stephentoub let me know if you think more things should be displayed here.

**Comment by stephentoub** [comment]
@tarekgh, for example, you've got a reader for in a local and you hover over it; presumably it'd be helpful if the debugger display tooltip showed you how many items were available to be read.

**Comment by tarekgh** [comment]
@stephentoub I got it.

**Comment by tarekgh** [comment]
#25026
#25162

**Comment by stephentoub** [comment]
At this point, all of the issues were addressed except for the vague "we can probably make this faster" part.  As such I'm going to close this.
