### ISSUE TITLE
System.IO.Compression.Brotli Epic

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#24826]
Tracking item for [System.IO.Compression.Brotli](https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Compression.Brotli)

Related #24174

**Comment by akoeplinger** [comment]
I'd be interested in getting a conclusion on https://github.com/dotnet/corefxlab/issues/1673 as part of this :)

**Comment by danmosemsft** [comment]
Cost from @ianhays

**Comment by ianhays** [comment]
# Design

- [X] Design the API for the non-allocating API
- [X] Design the API for BrotliStream
- [ ] Get final approval from LCA and add any required attributions
- [ ] Submit issue against CoreFX with API proposal for BrotliStream and Brotli

# Unit Testing
   
- [X] Abstract out the DeflateStream/GZipStream unit tests to be usable for any compression algorithm+
- [X] Add tests for any missing code coverage to the abstract CompressionStreamUnitTests
- [X] Test BrotliStream using the abstract CompressionStreamUnitTests
- [X] Add tests for the non-allocating API.
- [ ] Add tests that ensure interoperability with other Brotli implementations

# Perf Testing

- [X] Abstract out the DeflateStream/GZipStream performance tests to be usable for any compression algorithm
- [X] Test BrotliStream using the abstract CompressionStreamPerfTests
- [X] Add perf tests for the non-allocating API.
- [ ] Add the GoogleTestData to the current performance tests
- [ ] Compare new perf results between DeflateStream, BrotliStream, and the non-allocating API.

# Implementation - Managed Wrappers
- [X] Add new sln/csproj/Configurations/etc. in CoreFX
- [X] Add packaging stuff
- [X] Copy BrotliStream/BrotliStatic from CoreFXLab
- [X] Make any changes necessary to the above to get them to work in CoreFX
- [X] Spanify/Memoryify the implementations
- [X] Override the Async functions
- [ ] Do any final cleanup for the managed classes, remove all TODOs, correct all of the error message strings
- [ ] Bonus: Make _buffer rented
- [ ] Bonus: Add a special-case for one-shot encoding/decoding to use the BrotliDecoderDecompress/BrotliEncoderCompress functions

# Implementation - Windows Native
- [X] Port the c brotli code from Google into clrcompression
- [X] Add brotli into our Cmake files, exporting the functions that we're using in the managed wrappers
- [X] Fix any errors and test that the new imports/exports/details of the new clrcompressions are correct for every build config

# Implementation - Unix Native
- [ ] Decide whether to apt-get brotli or fit brotli into our current native compression package( which is just a shim right now)
- [ ] If we ship: Port brotli code to our unix package
- [ ] If we ship: Add brotli files and info to the Cmake unix builds
- [ ] If we ship: Fix any errors and test that the new imports/exports/details of the new non-shim dlls are correct for every build config
- [ ] If we apt-get, then add brotli to the apt-get scripts

**Comment by akoeplinger** [comment]
@ianhays so does this mean you decided on using a native brotli lib instead of a managed implementation?

**Comment by ianhays** [comment]
>so does this mean you decided on using a native brotli lib instead of a managed implementation?

Yes, though that does not preclude the eventual inclusion of a manged fallback. The primary drivers behind going the native route were:
- lower time to completion
- performance
- easier to update and take new fixes from google/brotli
- the hardest/most time consuming components of getting the native parts packaged are mostly already done because of zlib

I reasoned that because of the comparatively low cost of the native approach, it would be better to implement that first and have the product in a consumable state sooner rather than later. Then if we determine later that a managed implementation would be better, we can rip out the native one without hassle and replace it with a custom-written managed one. That way we also have a solid, tested baseline against which to test.
