### ISSUE TITLE
Complete MemoryExtensions Feature

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#24880]
- [x] Parity with Array APIs #25850
- [x] Move MemoryExtensions down to CoreLib #25182
- [x] MemoryExtensions.SequenceCompare #16878
- [x] ReadOnlySpan<char> string-like extension methods #21395

P2
- [x] String slice operations #24072

cc: @ahsonkhan, @joshfree

**Comment by KrzysztofCwalina** [comment]
Compare should either be vectorized or something similar to [ordinal string comparison](https://github.com/dotnet/coreclr/blob/8ec9b34df095df032e37b4c20a7359e9df7ae0ce/src/mscorlib/src/System/String.Comparison.cs#L222).

**Comment by stephentoub** [comment]
Related to #21395

**Comment by ahsonkhan** [comment]
All listed work items are done.
