### ISSUE TITLE
Promote netcoreapp tests to netstandard as possible

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#25083]
Tests that run only against .NET Standard surface area should run in the netstandard configuration so they can be reused against other netstandard implementations. It is likely that we currently have some tests running in the netcoreapp configuration that could be run in netstandard. We should do a pass through in order to beef up our netstandard coverage.

**Comment by ViktorHofer** [comment]
The following test projects should be promoted to netstandard as the corresponding source assembly builds against netstandard and is not a turd assembly (PNSE assembly):

- [ ] System.IO.FileSystem.AccessControl
- [ ] System.IO.Pipelines
- [ ] System.Json
- [ ] System.Numerics.Vectors
- [ ] System.Reflection.Metadata
- [ ] System.Security.Cryptography.Pkcs
- [ ] System.Threading.Tasks.Extensions

**Comment by stephentoub** [comment]
@ViktorHofer, is this issue still relevant?

**Comment by ViktorHofer** [comment]
No this isn't necessary anymore. Thanks.
