### ISSUE TITLE
Merge future branch back into master

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#2869]
This issue is just for tracking the changes we have merged into future so when we merge it back to master we know which API changes we need to modify contracts and ensure are supported on our other platforms like the desktop framework. At this point it isn't clear when this will happen but we want to keep track of this item.

--- Merged PRs into future ---
- [x] #1384 Regex group should provide a Name property.
- [x] #1783 Add ConcurrentDictionary GetOrAdd/AddOrUpdate overloads with generic arg
- [x] #1756 Implement generic interfaces on Regex collections
- [ ] #2436 Add async XLinq document/element loading and saving
- [x] #2862 Add HashSet<T> ctors with capacity

**Comment by karelz** [comment]
@weshaggard is it still needed?

**Comment by stephentoub** [comment]
I don't believe most of the above mentioned PRs/commits were ever brought back to master, but they were valid additions for approved new APIs.

**Comment by weshaggard** [comment]
Agreed. We should get these merged into master and added directly to .NET Core similar to what @ericstj  is doing in https://github.com/dotnet/corefx/pull/11272.

**Comment by Priya91** [comment]
> #1384 Regex group should provide a Name property.

This is in master, and also in full framework.

**Comment by karelz** [comment]
Updating the list to list of check boxes - marking #1384 as done per Priya's comment.

**Comment by justinvp** [comment]
Is this planned for the 1.2 timeframe? If so, should it be moved to the 1.2 milestone? If not, and I want to expose some of the new APIs for 1.2, should I just manually port those individual commits from Future to Master?

**Comment by karelz** [comment]
It will happen in 1.2, only if we have time. If you or anyone else wants to help, that would be great.

@weshaggard can you please confirm there is nothing preventing us to take ports of the changes into master? (i.e. if @justinvp or someone create the port, we can take it)

**Comment by weshaggard** [comment]
There shouldn't be anything blocking these APIs now. I suspect it will not be as simple as merging the changes to master. We will need to expose them as .NET Core app specific APIs.

**Comment by justinvp** [comment]
The following two can be checked off:
 - #1756 Implement generic interfaces on Regex collections (fixed by #12596)
 - #2862 Add HashSet<T> ctors with capacity (fixed by #12600)

**Comment by karelz** [comment]
Marked as such, thanks @justinvp!

**Comment by justinvp** [comment]
Now that #13828 has been merged, the ConcurrentDictionary change can be checked-off. The only remaining work item is:

 - [ ] #2436 Add async XLinq document/element loading and saving

**Comment by karelz** [comment]
Awesome, thank you very much @justinvp for your help!

**Comment by danmosemsft** [comment]
@sepidehMS please delete the branch once you merge your commit.
@weshaggard there were certainly other changes made in this brnach and I can't find a good way to make sure they were captured. I spot checked a couple and they were, so I trust your list...

**Comment by weshaggard** [comment]
I did generate the list fairly close to the time these were merged in the future branch so I think it captures all the API additions. If we did end up missing something I'm sure we can recreate or resurrect them later.

**Comment by sepidehMS** [comment]
@weshaggard Since future is a protected branch, is there anybody who has permissions to delete it? Or do I delete it via a PR?

**Comment by weshaggard** [comment]
Let me know when you are finished and I can delete it.

**Comment by sepidehMS** [comment]
> https://github.com/dotnet/corefx/pull/2436 Add async XLinq document/element loading and saving

@weshaggard I already merged the changes porting this last item in https://github.com/dotnet/corefx/issues/14774. So the branch can be deleted. Thank you.

**Comment by weshaggard** [comment]
future branch is deleted. For reference in the future here is a pointer to the sha it pointed at https://github.com/dotnet/corefx/commit/ee2d333.
