### ISSUE TITLE
Tracking items for System.Net.NameResolution

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#2891]
This issue is tracking TODOs and Shims removal for PR #2890 :
1. Contract changes to System.Net.Primitives:
   1. [ ] Add public ctor for `SocketException(SocketError errorCode, int platformError)`
   2. [ ] `IPAddress` - allow access to internal buffer via internal contract or new public API on `System.Net.Primitives`.
   3. [ ] `SocketAddress[int]` - allow direct access to internal buffer via internal contract or new public API in `System.Net.Primitives`.
2. Add UnitTests required by changes made during refactoring:
   1. [ ] `NameResolutionPal.GetHostByAddr(IPAddress)` : test with BIGENDIAN

**Comment by karelz** [comment]
Closing per triage discussion.

**Comment by stephentoub** [comment]
> Closing per triage discussion.

@karelz, there are still five TODOs in the codebase naming this issue.  Reopening...
