### ISSUE TITLE
UWP 6.2 size on disk optimizations

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#30597]
This is a running list of size on disk optimizations we're planning for UWP 6.2 to meet size on disk footprint targets set by the Windows team in a post-NetStandard 2.0 world.

- [x] Port https://github.com/dotnet/corert/commit/0ac83cb8d6f9ab10df616a608fcf6fdfa6eabe2b to CoreFX (#30598)
    - [x] Port to the release branch
- [x] Fix size regressions in `System.Linq` (3 MB size on disk saving for Maps) (#31025)
    - [x] Port to the release branch
- [x] Remove suspicious RD.XML from System.Private.Xml (#31125)
    - [x] Port to the release branch

[Removable feature](https://github.com/dotnet/designs/pull/42) annotations:
- [x] Make non-file URI resolving functionality in XmlUrlResolver optional (1.2 MB size on disk saving) (#31510) 
    - [x] Port to the release branch
- [X] Make reflection fallback in data contract serializers optional (350 kB size on disk saving) (#31533)
    - [x] Port to the release branch
- [ ] Make reflection fallback in XmlSerializaer optional (410 kB size on disk saving)
    - [ ] Port to the release branch

.NET Native compiler work (for completeness):

- [x] Respect removable feature annotations in the Dependency Reducer
    - [x] Expose option to specify removable features from project files/AppCompile
- [x] Add option to strip framework exception messages (400 kB size on disk saving)
    - [x] Expose option to strip framework exception messages from project files/AppCompile
    - [x] Make option to strip framework exception messages also respected on ARM64
- [x] Expose option to strip stack trace metadata from project files/AppCompile
- [x] Expose option to optimize for size from project files/AppCompile
- [x] Make the generic composition data that hangs off EETypes RVA-sized (instead of pointer-sized). (110 kB size on disk saving)
- [x] Add option to relax method body alignment requirement (1.5% size on disk saving)
    - [x] Expose option to relax method body alignment from project files/AppCompile
- [x] Add option to disable generation of dynamic invoke thunks (2% size on disk saving)
    - [x] Expose from project files/AppCompile

**Comment by MichalStrehovsky** [comment]
Cc @sergiy-k
