### ISSUE TITLE
Port xunit benchmark tests to BenchmarkDotNet

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#30734]
Date EOD estimated to be done with the respective task. May be the force be with us.

### 7/2/18
- [x] [System.Text.RegularExpressions.Performance.Tests](https://github.com/dotnet/performance/issues/71) (2-4 h)
- [x] [Perf_Marvin](https://github.com/dotnet/performance/issues/44) (1-2h)

### 7/3/18
- [x] [System.Runtime.Extensions.Performance.Tests](https://github.com/dotnet/performance/issues/64) (2-3h)
- [x] [System.Runtime.Serialization.Xml](https://github.com/dotnet/performance/issues/67) (1-3 h)
- [x] [System.Runtime.Numerics.Performance.Tests](https://github.com/dotnet/performance/issues/65) (1-2h)

### 7/5/18
- [x] [System.Runtime.Performance.Tests](https://github.com/dotnet/performance/issues/68) (1-2 days)

### 7/6/18
- [x] [System.Text.Encoding.Performance.Tests](https://github.com/dotnet/performance/issues/70) (1-2 h)
- [x] [Perf.TypeDescriptorTests](https://github.com/dotnet/performance/issues/48) (2 h)
- [x] [System.Runtime.Serialization.Json.Performance.Tests](https://github.com/dotnet/performance/issues/66) (1h) 

### 7/11/18 - Sytem.Collections
- [x] [System.Collections](https://github.com/dotnet/performance/issues/47) (1 day)
- [x] [System.Collections.Concurrent.Performance.Tests](https://github.com/dotnet/performance/issues/45) (1 day)
- [x] [System.Collections.NonGeneric.Performance.Tests](https://github.com/dotnet/performance/issues/46) (4 h)

### 7/13/18 - System.Threading
- [x] [System.Threading.Channels.Performance.Tests](https://github.com/dotnet/performance/issues/72) (1-2h)
- [x] [System.Threading.Tasks.Extensions.Performance.Tests](https://github.com/dotnet/performance/issues/73) (1-3h)
- [x] [System.Threading.Performance.Tests](https://github.com/dotnet/performance/issues/74) (2-4 h)

### 7/16/18 - System.Net
- [x] [System.Net.Http.Performance.Tests](https://github.com/dotnet/performance/issues/59) (1-2 h)
- [x] [System.Net.Primitives.Performance.Tests](https://github.com/dotnet/performance/issues/60) (1-2 h)
- [x] [System.Net.Sockets.Performance.Tests](https://github.com/dotnet/performance/issues/61) (1-2 h)

### 7/17/18
- [x] [System.Linq.Performance.Tests](https://github.com/dotnet/performance/issues/57) (2-6 h)

### 7/18/18 - System.IO.Compression
- [x] [System.IO.Compression.Brotli.Performance.Tests](https://github.com/dotnet/performance/issues/52) (2-4 h)
- [x] [System.IO.Compression.Performance.Tests](https://github.com/dotnet/performance/issues/53) (2-4 h)

### 7/20/18
- [x] [System.IO.FileSystem.Performance.Tests](https://github.com/dotnet/performance/issues/54) (2-4 h)
- [x] [System.IO.MemoryMappedFiles.Performance.Tests](https://github.com/dotnet/performance/issues/55) (1-2 h)
- [x] [System.IO.Pipes.Performance.Tests](https://github.com/dotnet/performance/issues/56) (1-4 h)

### 7/23/18
- [x] [System.Diagnostics.Process.Performance.Tests](https://github.com/dotnet/performance/issues/50) (1h – 1 day)
- [x] [System.Globalization.Performance.Tests](https://github.com/dotnet/performance/issues/51) (1-2h)

### 7/24/18
- [x] [System.Console.Performance.Tests](https://github.com/dotnet/performance/issues/49) (1 hour to 1 day)
- [x] [System.Security.Cryptography.Primitives.Performance.Tests](https://github.com/dotnet/performance/issues/69) (1-2 h)

### 7/25/18
- [x] [System.Numerics.Vectors.Performance.Tests](https://github.com/dotnet/performance/issues/62) (??)
- [x] [System.Xml.XmlDocument.Performance.Tests](https://github.com/dotnet/performance/issues/63) (1-2h)

### 7/27/18
- [x] [System.Memory.Performance.Tests](https://github.com/dotnet/performance/issues/58) (1-2 days)

**Comment by ViktorHofer** [comment]
cc @danmosemsft @valenis
