### ISSUE TITLE
Properly factor DllImports into Common\src\Interop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33774]
We now have a bunch of libraries with their own DllImports, whereas the expected approach is that all DllImports in product src should be included from src\Common\src\Interop, appropriately factored by platform and library, and then those source files included into the relevant assemblies that need them.

- [ ] Microsoft.Diagnostics.Tracing.EventSource.Redist
- [ ] System.Data.SqlClient
- [ ] System.Diagnostics.EventLog
- [ ] System.DirectoryServices
- [ ] System.DirectoryServices.AccountManagement
- [ ] System.DirectoryServices.Protocols
- [ ] System.Drawing.Common
- [ ] System.IO.Compression
- [ ] System.IO.Compression.Brotli
- [ ] System.IO.Ports
- [ ] System.Management
- [ ] System.Reflection.Metadata
- [ ] System.Runtime.Caching
- [ ] System.Security.Cryptography.Csp
- [ ] System.Security.Cryptography.Pkcs
- [ ] System.Security.Cryptography.X509Certificates

This all needs to be refactored and dedup'd.

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md

**Comment by Marusyk** [comment]
Hello, can I try to work on this?

**Comment by stephentoub** [comment]
@Marusyk, absolutely, thanks. I'd suggest starting with either EventLog, System.DirectoryServices.*, or System.Security.*.

**Comment by Marusyk** [comment]
Hello @stephentoub, 

Could you please check if I am on the proper way?
I start with [EventLog](https://github.com/Marusyk/corefx/commit/6f22d14ac0285ec1e4c7100753603033f6f199b2)

**Comment by stephentoub** [comment]
Thanks, @Marusyk!  That looks very good.  Please go ahead and create a PR for it so it can be properly reviewed and merged.

> should it be like one big PR or a few small ones?

One per library (e.g. EventLog) or family of libraries (e.g. System.DirectoryServices.*) would be good.

**Comment by StanislavUshakov** [comment]
Can I take `System.DirectoryServices`?

I have a couple of questions. As I can see there are a lot of `[DllImport]` for functions that are currently presented in src/Common/Interop, e.g. [LoadLibrary](https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/UnsafeNativeMethods.cs#L738), [GetProcAddress](https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/UnsafeNativeMethods.cs#L744) from "kernel32.dll" are duplicated. Also there is an internal class [LoadLibrarySafeHandle](https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/SafeHandle.cs#L32) which is a duplicate of `Common\CoreLib\Microsoft\Win32\SafeHandles\SafeLibraryHandle.cs`
So our steps are:
1. Remove duplicates from System.DirectoryServices and use methods and classes from src/Common.
2. Add non-existing methods to src/Common and remove them from System.DirectoryServices
3. If current DllImport method from src/Common/Interop doesn't have `SetLastError = true` and System.DirectoryServices needs it, we have to modify `Interop\Windows\kernel32\Interop.GetProcAddress.cs` (because it is used to throw an exception e.g. in [GetProcAddress with GetLastWin32Error](https://github.com/dotnet/corefx/blob/master/src/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Utils.cs#L112-L116))

If I am right with these assumptions, could you please take a look at [Refactored LoadLibrary, FreeLibrary, GetProcAddress](https://github.com/StanislavUshakov/corefx/commit/d49c231b82999bfe16b62312cc25fe9a13bfe3e9)
`using CommonInterop = Interop` is a temporary fix while we have Interop namespace in the project. I will remove it later.

**Comment by StanislavUshakov** [comment]
And another question: what are the differences between `Common/src/Interop/Windows` and `Common/src/CoreLib/Interop/Windows`?
Some methods are duplicated: [Interop.FreeLibrary in Common/src/Interop/Windows](https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/kernel32/Interop.FreeLibrary.cs) and [Interop.FreeLibrary in Common/src/CoreLib/Interop/Windows](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/Interop/Windows/Kernel32/Interop.FreeLibrary.cs) Which one should we use: from Common/src/Interop/Windows?
And what if there is no method in Common/src/Interop/Windows, but it exists in Common/src/CoreLib/Interop/Windows (e.g. [CloseHandle](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/Interop/Windows/Kernel32/Interop.CloseHandle.cs)) Can we reference this file?

**Comment by danmosemsft** [comment]
`Common/src/CoreLib/Interop/Windows` are mirrored from `src/System.Private.Corelib/shared/Interop/Windows` in the CoreCLR repo. Files there are there presumably because some code in System.Private.Corelib needs it. We mirror all of ``src/System.Private.Corelib/shared` from the CoreCLR repo so that any code in CoreFX can reuse it if it needs to. This falls in this category -- if there is duplication, then generally we would want to keep the corelib copy, and change CoreFX code to use that one, and delete the CoreFX copy. You can see examples of using files out of CoreFX's ``Common/src/CoreLib` in various project files in CoreFX.

**Comment by frbncis** [comment]
Hi! Can I take a crack at `System.DirectoryServices.Protocols`? There's a lot of them (~65), but it looks like it's mostly elbow grease.

**Comment by danmosemsft** [comment]
@frbncis sure - but we should take care, as our test coverage of that is mostly manual IIRC.

**Comment by satano** [comment]
Hello there. Can I take `System.Security.*`?

Also it would be nice to update the checkboxes in the issue to mark what was already done.

**Comment by satano** [comment]
Ping @danmosemsft, @stephentoub

**Comment by danmosemsft** [comment]
@satano thanks for the offer, please do. Are checkboxes correct now?

**Comment by satano** [comment]
I did not look into the sources, but according to the merged PR names, the checkboxes are correct. So I will look into `System.Security.Cryptography.X509Certificates`.

**Comment by danmosemsft** [comment]
OK!

**Comment by hareshambaliya** [comment]
@stephentoub I would like to contribute to this issue. Will you please guide me about where to start? What is pending?

**Comment by asayaipn** [comment]
hi all! can I take `System.Reflection.Metadata`?

**Comment by danmosemsft** [comment]
Sure go ahead!

**Comment by hareshambaliya** [comment]
@stephentoub Can I take System.DirectoryServices.AccountManagement?

I have questions too.
- What is `SafeNativeMethods` and `UnsafeNativeMethods`

**Comment by stephentoub** [comment]
> Will you please guide me about where to start? What is pending?

I've not recently audited progress here to see what's outstanding.  Basically you'd be looking for anywhere there are DllImports in product src not under the common interop folders.  Contributions are welcome :)
