### ISSUE TITLE
Tracking issues for System.Net.NetworkInformation and System.Net.Utilities

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#3562]
This issue is tracking TODOs and Shims removal for PR #:
- [ ] Replace Interop.\* with OS names from the SDK (iphlpapi)
- [ ] Unify error codes for Win32 (see Interop.ErrorCodes.cs in iphlpapi)
- [ ] Investigate DangerousAddRef then Dispose within `SafeCloseSocketAndEvent::CompleteInitialization(...)`
- [ ] In NetworkAddressChange.cs :

> @stephentoub:  We're invoking the user's callback while holding s_syncObject. There are trivial ways that could lead to deadlock (e.g. if the callback queued and waited on a work item that tried to add a handler), though maybe we don't care about such degenerate patterns?
- [ ] In NetworkAddressChange.cs: StartHelper()

> @ stephentoub: Is it not possible for both IPv4 and IPv6 to be supported and in the start options? If it is possible, we're overwriting statics that were just set in the previous section.
> 
> > @CIPop   Collaborator
> > CIPop added a note just now
> > Indeed, s_registeredWait is overwritten. There are other issues with this implementation: the RegisteredWaitHandle is never unregistered.

https://msdn.microsoft.com/en-us/library/w9f75h7a(v=vs.110).aspx:

> > > When you are finished using the RegisteredWaitHandle that is returned by this method, call its RegisteredWaitHandle.Unregister method to release references to the wait handle. We recommend that you always call the RegisteredWaitHandle.Unregister method, even if you specify true for executeOnlyOnce

**Comment by karelz** [comment]
Lots of nice to haves. We should attack them with general code clean up ... if we ever get to it.
