### ISSUE TITLE
Nullable: Issues found while annotating

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#36384]
This issue is to track various issues found while annotating for nullability.  Comments below group together the various issues discovered.

**Comment by krwq** [comment]
https://github.com/dotnet/coreclr/pull/23459#pullrequestreview-219146278

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/pull/23700

**Comment by stephentoub** [comment]
Places we throw NullReferenceException instead of ArgumentNullException due to not validating-and-throwing and just dereferencing:

- [ ] `CultureInfo.CreateSpecificCulture(string)` (https://github.com/dotnet/coreclr/pull/23459#pullrequestreview-219146278)
- [ ] CompareInfo.GetSortKey` (Unix in non invariant mode) - also possibly `GetHashCode`
- [ ] FileStream's ctors that take a SafeFileHandle

**Comment by stephentoub** [comment]
Functional (not argument validation bugs) found:

- [ ] MemoryStream.Capacity = 0 sets buffer to null when shrinking.  Fixed in https://github.com/dotnet/coreclr/pull/23700.

**Comment by krwq** [comment]
@stephentoub do you have context if this issue is still relevant? This does not feel like something we must address in 3.0?

**Comment by stephentoub** [comment]
We were just using it as a place to catalogue things we found along the way. I don't think there's any actual follow-up needed here. Let's close it.
