### ISSUE TITLE
Writable Json DOM

### ISSUE THREAD

**Issue by kasiabulat** [dotnet/corefx#39922]
Adding a modifiable API in `System.Text.Json` to complement the readonly `JsonDocumet`.

## Goals

* Designing API
* Implementation of provided methods
* Tests of provided methods
* Documentation for public API

## Specification
https://github.com/kasiabulat/corefx/pull/4/files#diff-554f8985f9d1787f6a1d12e4a6093778

**Comment by ahsonkhan** [comment]
Here's the work items left to do for this feature (in order/priority):
 - [ ] Merge this PR: https://github.com/dotnet/corefx/pull/41041
 - [ ] React to initial usability study feeback: https://github.com/dotnet/corefx/pull/41128
 - [ ] Improve code coverage: https://github.com/dotnet/corefx/issues/41130
 - [ ] Add support for Base64: https://github.com/dotnet/corefx/issues/41132
 - [ ] Add performance test and investigate perf gaps: https://github.com/dotnet/corefx/issues/41129    
 - [ ] Improve JsonNumber performance/internal implementation: https://github.com/dotnet/corefx/issues/39957
 - [ ] Investigate alternative design (making the `JsonNode` type hierarchy internal to `JsonElement` and unify the types) and conduct A/B usability study
 - [ ] Prototype and implement APIs that interop with `Utf8JsonReader`, `Utf8JsonWriter`, and `JsonSerializer`
 - [ ] API Review and react to any feedback from that
 - [ ] [might not apply if API shape changes] Implicit cast operators for JsonNumber: https://github.com/dotnet/corefx/issues/40118
 - [ ] [might not apply if API shape changes] Consider adding AggressiveInlining to JsonNode primitive types equality operator: https://github.com/dotnet/corefx/issues/40186
