### ISSUE TITLE
System.Net.Sockets TPL tracking items

### ISSUE THREAD

**Issue by josguil** [dotnet/corefx#4052]
- [ ] Optimize delegate allocations. 
- [x] Investigate behavior difference from Desktop: Used to throw SocketException.
- [x] Investigate behavior difference in tests in System.Net.Sockets.Legacy
