### ISSUE TITLE
Incorporate API review feedback for System.Net.* APIs

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#4732]
All networking APIs in .NET Core (System.Net, System.Net.Sockets, etc.) were recently reviewed by the API Review board. The detailed notes are here: https://github.com/dotnet/apireviews/pull/21

Filing this issue to track the following proposed changes based on API review feedback:

- [x] In `WebException` in the System.Net.Requests contract: For the constructors, change parameter name `inner`  to `innerException` to match that in .NET Framework - Done #4740 
- [x]  In `WinHttpHandler.ServerCertificateValidationCallback`: Document/add comments for the meaning of each parameter - Documentation bug referred to MSDN doc team
- [x] In types `NegotiateStream` and `SslStream`: Remove synchronous versions of `AuthenticateAsServer` and `AuthenticateAsClient` methods - Done #4868
- [x] In `System.Net.Utilities` contract: Consider if we want it to be a bag of multiple utilities OR more scoped down to just ICMP-related utilities. If scoped down, consider renaming the contract - Done #5232 renamed the contract to `System.Net.Ping`
- [x] Cancellation support: Add CancellationToken overloads to appropriate async methods in all contracts – e.g. `System.Net.Sockets`, `System.Net.Security` - Deferred #5211
- [x] In `enum SocketFlags`: Remove value `MaxIOVectorLength`, but document that slot 16 should not be used since it will cause conflict with .NET Framework - Done #4888
- [x] In `enum SocketOptionName`: Add ReuseUnicastPort support. This is a new option added to .NET Framework 4.6 to improve server scalability and is currently missing from .NET Core. - Done #4888
- [x] In structs `SocketReceiveFromResult` and `SocketReceiveMessageFromResult`: Investigate if the individual fields be properties. - Investigated. Final decision is to leave it as-is with public fields.

**Comment by SidharthNabar** [comment]
@davidsh @CIPop @josguil @pgavlin @stephentoub - PTAL

@roncain and @mconnew - PTAL to ensure that these changes (especially removal of the synchronous versions of AuthenticateAsServer and AuthenticateAsClient) do not break WCF dependencies

**Comment by mconnew** [comment]
Removing the sync methods won't be a blocker for us. I need to check to see if we use them, and if we do it's a simple matter of switching. Everything else won't block us.

**Comment by benaadams** [comment]
Related "Change System.Net.WebSockets contract for WebSocketReceiveResult" https://github.com/dotnet/corefx/issues/4530
