### ISSUE TITLE
System.Net Logging Tracking Items 

### ISSUE THREAD

**Issue by josguil** [dotnet/corefx#5144]
Tracking Items for https://github.com/dotnet/corefx/pull/5101

Formatting in *EventSource classes:
- [ ] Make constants have PascalCasing.
- [ ] Correctly separate arguments of methods in different lines (when needed).
- [ ] Add spaces needed in the attributes of the methods when not correctly aligned.
- [ ] New lines after if/else blocks (mainly after the IsEnabled check).

Dump Methods in SocketsEventSource:
- [ ] Analyse if the method type is necessary.Change if possible to receive a Socket (hash).
- [ ] Analyse if copying the buffer when it is received as an IntPtr to a byte [] is necessary. 
        Update: After trying in different ways, I couldn't make the event method work without making a copy to a byte[]. When using the predefined WriteEvent it would only log the address and not the array. I could not make an override method work properly. 

Keywords:
- [ ] Analyse if the right keywords are used for each event.

Logging.cs class
- [ ] Look for all the references done to this class in all projects and change calls to hash methods instead to LoggingHash.
- [ ] Delete Logging.cs (in both S:\corefx\src\Common\src\System\Net\Logging AND S:\corefx\src\common\src\system\net) 

Keep in sync with Localization:
- [ ]  https://github.com/dotnet/corefx/issues/5126

Testing
- [ ] Add some automated tests for the new EventSources created.

Compatibility
- [ ] Due to possible incompatibility between different versions of NetEventSource packaged inside distinct dlls, this class should not be changed in the future:

> The minute you have multiple copies of an EventSource that claim to be the same identity, you have the problem of who to 'believe' at runtime (each will send out a manifest for the events). Sure if they are the same, you are OK, but if they are in different modules, there is a pretty good chance they will ship at different times, and thus you might have machines that have one copy that is older than another. This creates a bunch of subtle error modes (new events may not be recognized) that would be very difficult to diagnose. We are trying to avoid subtlety like this.

Performance
- [x] Update System.Net.Sockets to avoid allocations/work at call sites when logging is disabled
- [x] Update System.Net.Security accordingly
- [x] Update System.Net.Ping accordingly
- [x] Update the rest of System.Net.\* accordingly
- [x] Remove GlobalLog.Assert(bool, ...) as it leads to bad habits

**Comment by jasonwilliams200OK** [comment]
@josguil, if you add a space between `[` and `]`, it will produce the proper check list: `- [ ]`. To mark it checked, you can either write markdown as `- [x]` or any collaborator/admin can click on the checkbox control in UI.

**Comment by josguil** [comment]
Thanks for the correction @jasonwilliams200OK

**Comment by jasonwilliams200OK** [comment]
@josguil, no problem. I have removed the comment so the task count in issue tracker (https://github.com/dotnet/corefx/issues) does not mislead the surfers. :)

**Comment by SidharthNabar** [comment]
These are TODO items to improve the current logging PR that enables logging for .NET Core. Given the current timeline, this will be worked on after RTM milestone.

**Comment by CIPop** [comment]
Not all issues closed by #5151

**Comment by CIPop** [comment]
@stephentoub I believe you've already addressed all the issues above with #13134. 

Please reopen if you believe any of the tracked items above are still required.
