### ISSUE TITLE
Update UWP meta-packages and lineups

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5843]
As part of the NETStandard work we had to rebaseline all of our package dependencies to versions that have support for NETStandard.

In doing so this would have normally broken shared library since it requires that the versions of some assemblies explicitly match those that were pre-compiled to native in the shared assembly.  To avoid that I am producing packages that redist the old DLLs in the new format.  We'll need to roll up these packages in a few ways.

We're also shipping a minor change to the UWP meta-package in update 2 that delivers a few bugfixes.

Here's an inventory of the versions we have and will need to produce:
MS.NETCore.UWP : 5.0.0 -- RTM
MS.NETCore.UWP : 5.1.0 -- Minor bugfixes, still using old package format, supports shared library.
  -- no update to lineup
  -- new default for file > new project
MS.NETCore.UWP : 5.2.0 -- Lots of new API, using new netstandard monikers, supports shared library.
  -- requires an update to the UWP lineup as well
MS.NETCore.UWP : 5.3.0 -- Similar to 5.2.0 but also includes all the API and implementation changes to things in shared library.
  -- update to the lineup

We'd also like to ship a pre-version NETStandard.Library that allows folks to build against a set of API that will not break shared library.  Related to https://github.com/dotnet/corefx/issues/5216.

**Comment by muratg** [comment]
:eyes:

**Comment by ericstj** [comment]
Just to be clear, this work will not block the netstandard transition but it is something that we need to do to complete the story with UWP.

**Comment by muratg** [comment]
Yup agreed. I think EF may care about this one.

**Comment by ericstj** [comment]
We've changed the plan here.  Previously we were going to try to hide shared library in package versions but that's turned out to be too complicated.  Instead we're going to fix UWP to a specific generation and redistribute the implementations of the contracts for those libraries that are in shared library.

As such we've asked NuGet to map UWP to netstandard1.4: https://github.com/NuGet/Home/issues/2273

The remaining work is:
 - [ ] Pick up the new version of NuGet in buildtools.
 - [ ] Delete baseline redist packages
 - [ ] Include UWP redist libs in any package that's part of shared library.
 - [ ] Update NETStandard version for any contract that cannot be supported by UWP shared library to NetStandard 1.5: 
    - System.Diagnostics.Tracing
    - System.IO
    - System.Reflection.TypeExtensions
    - System.Runtime
    - System.Runtime.InteropServices
    - System.Reflection
 - [ ] Update baseline targets in buildtools to latest packages.

Once done targeting UWP will be automatic when targeting NETStandard1.4 or lower.  Folks won't need to do anything special with dependency versions.  It also means that NETStandard1.5 cannot be used if folks want to target UWP, but that's the reality of shared library at the moment.

**Comment by onovotny** [comment]
Few questions here -- possibly not related directly to this issue:

  - Does this mean that UWP will be updated over time to support a later NetStandard version? So hypothetically, in the fall some UWP tooling update would enable NetStandard1.5? Would that also require a NuGet update?
  - What does this mean for the reflection issue in #6684? Does this mean that the ref assms for all NetStandard versions will be available to all NetStandard 1.4 runtimes, at least for reflection purposes?

Thanks

**Comment by ericstj** [comment]
> Does this mean that UWP will be updated over time to support a later NetStandard version? 

Yes, once a new shared library is created we can have UWP target a new standard library.  It will require a nuget update.

This has no impact on https://github.com/dotnet/corefx/issues/6684.  No impact on https://github.com/dotnet/corefx/issues/2576, either.

**Comment by ericstj** [comment]
It turns out that I needed to fix https://github.com/dotnet/corefx/issues/5842 as part of this because we can't have newer version reference assemblies than the UWP implementation assemblies.

Here's the buildtools changes: https://github.com/dotnet/buildtools/pull/533
And corefx: https://github.com/ericstj/corefx/tree/UWP-netstandard1.4

**Comment by ericstj** [comment]
This has been fixed by #6902

**Comment by gulbanana** [comment]
I'm confused, how can UWP be updated someday to netstandard15 if netstandard15 contains System.IO?

**Comment by ericstj** [comment]
System.IO is in every version of NETStandard.  NETStandard1.5 added some new API to System.IO vs the API that was available in NETStandard1.4.  That API is expressed in the assembly version 4.1.0.0 vs 4.0.10.0 as shown by this table: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-net-corefx-apis-and-their-associated-net-platform-standard-version

**Comment by gulbanana** [comment]
Makes sense, but does that mean UWP will never support NETStandard1.5?

**Comment by gulbanana** [comment]
My concern here is that NETStandard1.5/later contains other api which *can* be supported in a sandbox environment, and I would like to build libraries which use that API and can be used in Store apps.

**Comment by weshaggard** [comment]
@gulbanana yes it is a goal for us to make UWP apps support a higher netstandard version but it isn't clear when we will be able to do that yet because it requires not only updates to the library packages but also updates to the UWP tool chain which need to be in-sync.

**Comment by gulbanana** [comment]
Ouch. Well, good luck bringing the threads together.
