### ISSUE TITLE
Improve negative tests in System.Globalization.Calendars

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6775]
### Context
I have done work in #6733 for consolidating common negative tests for Calendars exposed in corefx. The implementation is generic, and should support all calendars.

### Todo
There are some issues to be investigated:
- [x] JapenseLunisolarCalendar is not supported. This is because the implementation calculates that the `MaximumCalendarYearInEra(new JapaneseLunisolarCalendar(), 3)` is 1, not as 64 (IIRC) expected. This can be fixed by changing the code from
`return calendar.GetYear(calendar.ToDateTime(1, 1, 1, 0, 0, 0, 0, era + 1).AddDays(-1)) + 1;` to `return calendar.GetYear(calendar.ToDateTime(1, 1, 1, 0, 0, 0, 0, era + 1).AddMonths(-1)) + 1;`, but this reduces the versatility of existing tests.
- [ ] `GetDayOfWeek_Invalid` should not be tested for Lunar and lunarsolar calendars, as the method doesn't throw on these calendars. There is no way in corefx to check if a calendar is lunarsolar
- [ ] `GetEra_Invalid` throws an exception for most calendars, but not HebrewCalendar, TaiwanLunisolarCalendar and JapaneseLunisolarCalendar. Maybe this is a similar cause from the previous point

### Further ideas
Some further ideas that are nice but not so important
- Test each year, and invalid months outside the max and min month in each year
- Test each month, and invalid days outside the max and min day in each month

/cc @tarekgh

**Comment by hughbe** [comment]
@tarekgh nice one on the Japanese fix - maybe the getera test failures are bugs as well?

**Comment by tarekgh** [comment]
@hughbe  I'll take a look at some point too to make sure all good.
